from trade.models import all_trades
from total_statistics.models import statistics
from django.views.decorators.csrf import csrf_exempt
from . import utiliites
from django.http import HttpResponse
import time
import ipdb


@csrf_exempt
def deleteHistory(request):
    all_trades.objects.all().delete()
    statistics.objects.all().delete()

    return HttpResponse("DELETE HISTORY")


@csrf_exempt
def getSingleStockCandles(request):
    allStockNames = [
        # "ACBI",
        "BDSI",
        "BKEP",
        "BKEPP",
        "ALT",
        "AACG",
        "AAL",
        "AAME",
        "AAOI",
        "AAON",
        "AAPL",
        "AATC",
        "AAWW",
        "ABCB",
        "ABEO",
        "ABIO",
        "ABST",
        "ABTX",
        "ABUS",
        "ACB",
        "ACER",
        "ACGL",
        "ACGLO",
        "ACHC",
        "ACHV",
        "ACIU",
        "ACIW",
        "ACLS",
        "ACB",
        "ACMR",
        "ACNB",
        "ACOR",
        "ACRS",
        "ACRX",
        "ACST",
        "ACTG",
        "ADAP",
        "ADBE",
        "ADES",
        "ADI",
        "ADMA",
        "ADMP",
        "ADP",
        "ADSK",
        "ADTN",
        "ADUS",
        "ADVM",
        "ADXS",
        "AEHL",
        "AEHR",
        "AEIS",
        "AEMD",
        "AEP",
        "AERI",
        "AESE",
        "AEYE",
        "AEZS",
        "AFBI",
        "AFMD",
        "AGFS",
        "AGIO",
        "AGRX",
        "AGTC",
        "AGYS",
        "AHPI",
        "AIKI",
        "AIMC",
        "AINV",
        "AIRG",
        "AIRT",
        "AKAM",
        "AKBA",
        "AKTS",
        "AKTX",
        "ALGN",
        "ALGT",
        "ALJJ",
        "ALKS",
        "ALLT",
        "ALNY",
        "ALOT",
        "ALPN",
        "ALPP",
        # "ALRM",
        # "ALRN",
        # "ALRS",
        # "ALTO",
        # "ALTR",
        # "ALYA",
        # "AMAT",
        # "AMBA",
        # "AMCX",
        # "AMD",
        # "AMED",
        # "AMEH",
        # "AMGN",
        # "AMKR",
        # "AMNB",
        # "AMOT",
        # "AMPH",
        # "AMRK",
        # "AMRN",
        # "AMRS",
        # "AMSC",
        # "AMSF",
        # "AMWD",
        # "AMZN",
        # "ANAB",
        # "ANAT",
        # "ANDE",
        # "ANGI",
        # "ANSS",
        # "ANTE",
        # "ANY",
        # "AOSL",
        # "APA",
        # "APDN",
        # "APEI",
        # "APEN",
        # "APLS",
        # "APOG",
        # "APPF",
        # "APPN",
        # "APPS",
        # "APTO",
        # "APVO",
        # "APWC",
        # "AQB",
        # "AQMS",
        # "ARAV",
        # "ARAY",
        # "ARCB",
        # "ARCC",
        # "ARCT",
        # "AREC",
        # "ARGX",
        # "ARTNA",
        # "ASND",
        # "ASPU",
        # "ASTC",
        # "ASUR",
        # "ATEX",
        # "ATHE",
        # "ATLC",
        # "ATNI",
        # "ATOS",
        # "ATRC",
        # "ATRO",
        # "ATVI",
        # "ATXI",
        # "ATXS",
        # "AUB",
        # "AUBN",
        # "AUDC",
        # "AUPH",
        # "AUTO",
        # "AVAV",
        # "AVCT",
        # "AVDL",
        # "AVEO",
        # "AVGO",
        # "AVGR",
        # "AVID",
        # "AVNW",
        # "AVT",
        # "AVTX",
        # "AVXL",
        # "AWH",
        # "AWRE",
        # "AXDX",
        # "AXGN",
        # "AXON",
        # "AXSM",
        # "AXTI",
        # "AY",
        # "AYRO",
        # "AYTU",
        # "AZN",
        # "AZPN",
        # "BAND",
        # "BANF",
        # "BANFP",
        # "BANR",
        # "BANX",
        # "BATRK",
        # "BBBY",
        # "BBCP",
        # "BBGI",
        # "BBI",
        # "BBQ",
        # "BBSI",
        # "BCBP",
        # "BCDA",
        # "BCLI",
        # "BCML",
        # "BCOR",
        # "BCOV",
        # "BCPC",
        # "BCRX",
        # "BCTX",
        # "BECN",
        # "BEEM",
        # "BELFA",
        # "BELFB",
        # "BFC",
        # "BFIN",
        # "BGCP",
        # "BGFV",
        # "BGNE",
        # "BHF",
        # "BIDU",
        # "BIIB",
        # "BIMI",
        # "BIOC",
        # "BIOL",
        # "BJRI",
        # "BKCC",
        # "BKNG",
        # "BKSC",
        # "BKYI",
        # "BL",
        # "BLBD",
        # "BLCM",
        # "BLDP",
        # "BLFS",
        # "BLIN",
        # "BLKB",
        # "BLMN",
        # "BLNK",
        # "BLPH",
        # "BLRX",
        # "BLU",
        # "BLUE",
        # "BMRA",
        # "BMRC",
        # "BMRN",
        # "BNFT",
        # "BNSO",
        # "BNTC",
        # "BOKF",
        # "BOMN",
        # "BOOM",
        # "BOSC",
        # "BOTJ",
        # "BOXL",
        # "BPMC",
        # "BPOP",
        # "BPOPM",
        # "BPRN",
        # "BPTH",
        # "BRCN",
        # "BRID",
        # "BRKL",
        # "BRKR",
        # "BRQS",
        # "BSCM",
        # "BSCN",
        # "BSCO",
        # "BSCP",
        # "BSCQ",
        # "BSCR",
        # "BSET",
        # "BSGM",
        # "BSJM",
        # "BSJN",
        # "BSJO",
        # "BSJP",
        # "BSQR",
        # "BSRR",
        # "BTB",
        # "BTCS",
        # "BTEC",
        # "BTX",
        # "BUSE",
        # "BVXV",
        # "BWEN",
        # "BWFG",
        # "BYFC",
        # "BYRN",
        # "BYSI",
        # "BZUN",
        # "CAAS",
        # "CAC",
        # "CACC",
        # "CACG",
        # "CAKE",
        # "CALA",
        # "CALM",
        # "CAMP",
        # "CAMT",
        # "CAPR",
        # "CAR",
        # "CARA",
        # "CARE",
        # "CARG",
        # "CARV",
        # "CARZ",
        # "CASA",
        # "CASH",
        # "CASI",
        # "CASS",
        # "CASY",
        # "CATC",
        # "CATH",
        # "CATY",
        # "CBAN",
        # "CBAT",
        # "CBAY",
        # "CBFV",
        # "CBIO",
        # "CBRL",
        # "CBSH",
        # "CBTX",
        # "CCBG",
        # "CCD",
        # "CCEP",
        # "CCLP",
        # "CCMP",
        # "CCNE",
        # "CCOI",
        # "CCRN",
        # "CCXI",
        # "CDC",
        # "CDEV",
        # "CDK",
        # "CDL",
        # "CDMO",
        # "CDNA",
        # "CDNS",
        # "CDTX",
        # "CDW",
        # "CDXC",
        # "CDXS",
        # "CDZI",
        # "CECE",
        # "CELC",
        # "CELH",
        # "CEMI",
        # "CENT",
        # "CENTA",
        # "CENX",
        # "CERN",
        # "CERS",
        # "CETX",
        # "CETXP",
        # "CEVA",
        # "CEY",
        # "CFA",
        # "CFBK",
        # "CFFI",
        # "CFFN",
        # "CFMS",
        # "CFO",
        # "CFRX",
        # "CG",
        # "CGBD",
        # "CGC",
        # "CGEN",
        # "CGNX",
        # "CGO",
        # "CGRN",
        # "CHCI",
        # "CHCO",
        # "CHDN",
        # "CHEF",
        # "CHEK",
        # "CHKP",
        # "CHMG",
        # "CHNR",
        # "CHRS",
        # "CHRW",
        # "CHSCL",
        # "CHSCM",
        # "CHSCN",
        # "CHSCO",
        # "CHSCP",
        # "CHTR",
        # "CHUY",
        # "CHW",
        # "CHY",
        # "CIBR",
        # "CID",
        # "CIDM",
        # "CIGI",
        # "CIL",
        # "CINF",
        # "CIVB",
        # "CIZ",
        # "CLBS",
        # "CLDX",
        # "CLIR",
        # "CLLS",
        # "CLPT",
        # "CLRB",
        # "CLRG",
        # "CLRO",
        # "CLSD",
        # "CLSK",
        # "CLSN",
        # "CLXT",
        # "CMCO",
        # "CMCSA",
        # "CMCT",
        # "CME",
        # "CMPR",
        # "CMRX",
        # "CNCE",
        # "CNCR",
        # "CNDT",
        # "CNET",
        # "CNFR",
        # "CNOB",
        # "CNSL",
        # "CNTY",
        # "CNXN",
        # "COCP",
        # "CODA",
        # "CODX",
        # "COFS",
        # "COHR",
        # "COHU",
        # "COKE",
        # "COLB",
        # "COLL",
        # "COLM",
        # "COMM",
        # "COMS",
        # "COMT",
        # "CONE",
        # "CONN",
        # "COOP",
        # "CORT",
        # "COST",
        # "COUP",
        # "COWN",
        # "CPHC",
        # "CPIX",
        # "CPLP",
        # "CPRT",
        # "CPRX",
        # "CPSH",
        # "CPSI",
        # "CPSS",
        # "CPTAG",
        # "CPTAL",
        # "CRAI",
        # "CRBP",
        # "CRDF",
        # "CREG",
        # "CRESY",
        # "CREX",
        # "CRIS",
        # "CRMD",
        # "CRMT",
        # "CROX",
        # "CRSP",
        # "CRTO",
        # "CRUS",
        # "CRVL",
        # "CRVS",
        # "CRWS",
        # "DBVT",
        # "DCOM",
        # "DCPH",
        # "DGICA",
        # "DGII",
        # "DGLY",
        # "DGRE",
        # "DGRS",
        # "DGRW",
        # "DHCNI",
        # "DIOD",
        # "DISCA",
        # "DISCB",
        # "DISCK",
        # "DISH",
        # "DJCO",
        # "DLHC",
        # "DLPN",
        # "DLTH",
        # "DLTR",
        # "DMAC",
        # "DMLP",
        # "DMRC",
        # "DMTK",
        # "DNLI",
        # "DOGZ",
        # "DOOO",
        # "DORM",
        # "DOX",
        # "DRIO",
        # "DRRX",
        # "DRTT",
        # "DSGX",
        # "DSKE",
        # "DSWL",
        # "DTEA",
        # "DTST",
        # "DUOT",
        # "DVY",
        # "DWAS",
        # "DWAT",
        # "DWPP",
        # "DWSN",
        # "DXCM",
        # "DYNT",
        # "DZSI",
        # "EA",
        # "EAST",
        # "EBAY",
        # "EBIX",
        # "EBMT",
        # "ECPG",
        # "EDAP",
        # "EDIT",
        # "EDSA",
        # "EDUC",
        # "EEFT",
        # "EEMA",
        # "EFAS",
        # "EFOI",
        # "EGAN",
        # "EGBN",
        # "EGLE",
        # "EGRX",
        # "EMIF",
        # "EMKR",
        # "EML",
        # "EMXC",
        # "ENDP",
        # "ENG",
        # "ENLV",
        # "ENVB",
        # "ENZL",
        # "EPAY",
        # "EPIX",
        # "EPSN",
        # "EPZM",
        # "EQBK",
        # "EQIX",
        # "EQRR",
        # "ERIC",
        # "ERIE",
        # "ERII",
        # "ERYP",
        # "ESBK",
        # "ESCA",
        # "ESEA",
        # "ESGD",
        # "ESGE",
        # "ESGR",
        # "ESGU",
        # "ESLT",
        # "ESPR",
        # "ESQ",
        # "ESSA",
        # "ETSY",
        # "EUFN",
        # "EVBG",
        # "EVFM",
        # "EVO",
        # "EVOK",
        # "EVOL",
        # "EWBC",
        # "EWZS",
        # "EXAS",
        # "EXC",
        # "EXEL",
        # "EXLS",
        # "EXPD",
        # "EXPE",
        # "EXPO",
        # "EXTR",
        # "EYE",
        # "EYES",
        # "EYPT",
        # "EZPW",
        # "FAAR",
        # "FAB",
        # "FAD",
        # "FALN",
        # "FANG",
        # "FANH",
        # "FARM",
        # "FARO",
        # "FAST",
        # "FAT",
        # "FATE",
        # "FB",
        # "FBIO",
        # "FBIOP",
        # "FBIZ",
        # "FBMS",
        # "FBNC",
        # "FBRX",
        # "FBZ",
        # "FCA",
        # "FCAL",
        # "FCAP",
        # "FCBC",
        # "FCCO",
        # "FCCY",
        # "FCEF",
        # "FCEL",
        # "FCFS",
        # "FCNCA",
        # "FCRD",
        # "FCVT",
        # "FDBC",
        # "FDIV",
        # "FDT",
        # "FDTS",
        # "FDUS",
        # "FEIM",
        # "FELE",
        # "FEM",
        # "FEMB",
        # "FEMS",
        # "FENC",
        # "FEP",
        # "FEUZ",
        # "FEX",
        # "FFBC",
        # "FFBW",
        # "FFHL",
        # "FFIC",
        # "FFIN",
        # "FFIV",
        # "FFNW",
        # "FFWM",
        # "FGBI",
        # "FGEN",
        # "FGF",
        # "FID",
        # "FINX",
        # "FISI",
        # "FISV",
        # "FITB",
        # "FITBI",
        # "FIVE",
        # "FIVN",
        # "FIXD",
        # "FIZZ",
        # "FJP",
        # "FKU",
        # "FKWL",
        # "FLDM",
        # "FLEX",
        # "FLGT",
        # "FLIC",
        # "FLL",
        # "FLMN",
        # "FLNT",
        # "FLXS",
        # "FMAO",
        # "FMB",
        # "FMBH",
        # "FMBI",
        # "FMHI",
        # "FMNB",
        # "FNCB",
        # "FNHC",
        # "FNK",
        # "FNKO",
        # "FNLC",
        # "FNWB",
        # "FNWD",
        # "FNX",
        # "FNY",
        # "FOLD",
        # "FONR",
        # "FORD",
        # "FORM",
        # "FORR",
        # "FORTY",
        # "FOSL",
        # "FOXF",
        # "FPA",
        # "FPAY",
        # "FPXI",
        # "FRAF",
        # "FRBA",
        # "FRBK",
        # "FRGI",
        # "FRME",
        # "FRPH",
        # "FRPT",
        # "FRSX",
        # "FRTA",
        # "FSBW",
        # "FSFG",
        # "FSLR",
        # "FSTR",
        # "FSTX",
        # "FSV",
        # "FSZ",
        # "FTA",
        # "FTAG",
        # "FTC",
        # "FTCS",
        # "FTEK",
        # "FTFT",
        # "FTGC",
        # "FTHI",
        # "FTLB",
        # "FTNT",
        # "FTSL",
        # "FTSM",
        # "FTXD",
        # "FTXG",
        # "FTXH",
        # "FTXL",
        # "FTXN",
        # "FTXO",
        # "FTXR",
        # "FULT",
        # "FUNC",
        # "FUND",
        # "FUSB",
        # "FUV",
        # "FV",
        # "FVC",
        # "FVCB",
        # "FVE",
        # "FWBI",
        # "FWONA",
        # "FWP",
        # "FWRD",
        # "FXNC",
        # "FYC",
        # "FYT",
        # "FYX",
        # "GAIA",
        # "GAIN",
        # "GALT",
        # "GASS",
        # "GBCI",
        # "GBDC",
        # "GBLI",
        # "GBOX",
        # "GBT",
        # "GCBC",
        # "GDEN",
        # "GDS",
        # "GECC",
        # "GEG",
        # "GENC",
        # "GENE",
        # "GENY",
        # "GEOS",
        # "GERN",
        # "GGAL",
        # "GIFI",
        # "GIGM",
        # "GIII",
        # "GILD",
        # "GILT",
        # "GLAD",
        # "GLBS",
        # "GLBZ",
        # "GLDD",
        # "GLDI",
        # "GLG",
        # "GLMD",
        # "GLNG",
        # "GLPG",
        # "GRBK",
        # "GREE",
        # "GRFS",
        # "GRID",
        # "GRMN",
        # "GROM",
        # "GROW",
        # "GRPN",
        # "GRVY",
        # "GSBC",
        # "GSIT",
        # "GSM",
        # "GT",
        # "GTHX",
        # "GTIM",
        # "GTYH",
        # "GURE",
        # "GVP",
        # "GWGH",
        # "GWRS",
        # "GYRO",
        # "HA",
        # "HAFC",
        # "HAIN",
        # "HALL",
        # "HALO",
        # "HAS",
        # "HAYN",
        # "HBAN",
        # "HBCP",
        # "HBIO",
        # "HBMD",
        # "HBNC",
        # "HBP",
        # "HCCI",
        # "HCKT",
        # "HCM",
        # "HCSG",
        # "HDSN",
        # "HEAR",
        # "HEES",
        # "HELE",
        # "HEPA",
        # "HEWG",
        # "HFBL",
        # "HFFG",
        # "HFWA",
        # "HGBL",
        # "HGEN",
        # "HGSH",
        # "HIBB",
        # "HIFS",
        # "HIHO",
        # "HIMX",
        # "HLNE",
        # "HMHC",
        # "HMNF",
        # "HMST",
        # "HMTV",
        # "HNNA",
        # "HNRG",
        # "HOFT",
        # "HOLI",
        # "HOLX",
        # "HOMB",
        # "HON",
        # "HONE",
        # "HOPE",
        # "HOVNP",
        # "HQY",
        # "HROW",
        # "HRTX",
        # "HRZN",
        # "HSDT",
        # "HTBK",
        # "HTBX",
        # "HTGM",
        # "HTHT",
        # "HTLD",
        # "HTLF",
        # "HUBG",
        # "HURC",
        # "HURN",
        # "HUSN",
        # "HVBC",
        # "HWBK",
        # "HWC",
        # "HWKN",
        # "HYXF",
        # "HYZD",
        # "HZNP",
        # "IAC",
        # "IART",
        # "IBB",
        # "IBKR",
        # "IBOC",
        # "IBRX",
        # "IBTX",
        # "ICAD",
        # "ICCC",
        # "ICFI",
        # "ICHR",
        # "ICLK",
        # "ICLN",
        # "ICLR",
        # "ICMB",
        # "ICPT",
        # "ICUI",
        # "IDCC",
        # "IDEX",
        # "IDLB",
        # "IDRA",
        # "IDXX",
        # "IEA",
        # "IEF",
        # "IEI",
        # "IEP",
        # "IESC",
        # "IGF",
        # "IGIB",
        # "IGOV",
        # "IGSB",
        # "III",
        # "IIN",
        # "IIVI",
        # "IJT",
        # "ILMN",
        # "IMBI",
        # "IMCV",
        # "IMGN",
        # "IMKTA",
        # "IMMP",
        # "IMMR",
        # "IMOS",
        # "IMRN",
        # "IMTE",
        # "IMUX",
        # "IMV",
        # "IMXI",
        # "INBK",
        # "INCY",
        # "INDB",
        # "INDP",
        # "INDT",
        # "INDY",
        # "INFI",
        # "INFN",
        # "INFR",
        # "INGN",
        # "INM",
        # "INO",
        # "INOD",
        # "INPX",
        # "INSE",
        # "INSG",
        # "INSM",
        # "INTC",
        # "INTG",
        # "INTU",
        # "INTZ",
        # "INVA",
        # "INVE",
        # "IONS",
        # "IOSP",
        # "IOVA",
        # "IPA",
        # "IPAR",
        # "IPDN",
        # "IPGP",
        # "IPKW",
        # "IPWR",
        # "IRBT",
        # "IRCP",
        # "IRDM",
        # "IRIX",
        # "IRMD",
        # "IROQ",
        # "IRTC",
        # "IRWD",
        # "ISBC",
        # "ISEE",
        # "ISRG",
        # "ISSC",
        # "ISTB",
        # "ISTR",
        # "ISUN",
        # "ITCI",
        # "ITI",
        # "ITIC",
        # "ITRI",
        # "ITRN",
        # "IUSB",
        # "IUSG",
        # "IUSV",
        # "IVAC",
        # "JAZZ",
        # "JBHT",
        # "JBLU",
        # "JBSS",
        # "JCS",
        # "JCTCF",
        # "JD",
        # "JJSF",
        # "JKHY",
        # "JNCE",
        # "JOUT",
        # "JRJC",
        # "JRVR",
        # "JSM",
        # "JSMD",
        # "JSML",
        # "JVA",
        # "JYNT",
        # "KALA",
        # "KALU",
        # "KALV",
        # "KBWB",
        # "KBWD",
        # "KBWP",
        # "KBWR",
        # "KBWY",
        # "KDNY",
        # "KDP",
        # "KE",
        # "KELYA",
        # "KEQU",
        # "KFFB",
        # "KFRC",
        # "KHC",
        # "KIDS",
        # "KINS",
        # "KIRK",
        # "KLAC",
        # "KLIC",
        # "KMDA",
        # "KMPH",
        # "KNDI",
        # "KNSL",
        # "KOPN",
        # "KOR",
        # "KOSS",
        # "KPTI",
        # "KRMA",
        # "KRMD",
        # "KRNT",
        # "KRNY",
        # "KRYS",
        # "KSPN",
        # "KTCC",
        # "KTOS",
        # "KTRA",
        # "KURA",
        # "KVHI",
        # "KXIN",
        # "KZIA",
        # "LAKE",
        # "LAMR",
        # "LANC",
        # "LAND",
        # "LARK",
        # "LAUR",
        # "LAWS",
        # "LBAI",
        # "LBC",
        # "LBRDA",
        # "LBRDK",
        # "LBTYA",
        # "LBTYB",
        # "LBTYK",
        # "LCNB",
        # "LCUT",
        # "LE",
        # "LECO",
        # "LEDS",
        # "LEE",
        # "LFMD",
        # "LFUS",
        # "LFVN",
        # "LGIH",
        # "LGND",
        # "LGO",
        # "LHCG",
        # "LIFE",
        # "LILA",
        # "LILAK",
        # "LINC",
        # "LIND",
        # "LINK",
        # "LIQT",
        # "LITE",
        # "LIVE",
        # "LIVN",
        # "LIXT",
        # "LJPC",
        # "LKFN",
        # "LKQ",
        # "LLL",
        # "LLNW",
        # "LMAT",
        # "LMB",
        # "LMBS",
        # "LMFA",
        # "LMNL",
        # "LMNR",
        # "LMST",
        # "LNDC",
        # "LNT",
        # "LNTH",
        # "LOAN",
        # "LOB",
        # "LOCO",
        # "LOGI",
        # "LOOP",
        # "LOPE",
        # "LPCN",
        # "LPLA",
        # "LPSN",
        # "LPTH",
        # "LPTX",
        # "LQDT",
        # "LRCX",
        # "LRFC",
        # "LRGE",
        # "LRMR",
        # "LSBK",
        # "LSCC",
        # "LSTR",
        # "LSXMA",
        # "LSXMB",
        # "LSXMK",
        # "LTBR",
        # "LTRPA",
        # "LTRX",
        # "LULU",
        # "LUMO",
        # "LUNA",
        # "LVHD",
        # "LVO",
        # "LWAY",
        # "LWLG",
        # "LX",
        # "LXRX",
        # "LYL",
        # "LYTS",
        # "MACK",
        # "MANH",
        # "MANT",
        # "MARA",
        # "MARK",
        # "MASI",
        # "MAT",
        # "MATW",
        # "MAYS",
        # "MBB",
        # "MBCN",
        # "MBII",
        # "MBIN",
        # "MBIO",
        # "MBOT",
        # "MBRX",
        # "MBUU",
        # "MBWM",
        # "MCBC",
        # "MCEF",
        # "MCFT",
        # "MCHI",
        # "MCHP",
        # "MCHX",
        # "MCRB",
        # "MCRI",
        # "MDB",
        # "MDGL",
        # "MDGS",
        # "MDIV",
        # "MDLZ",
        # "MDRX",
        # "MDVL",
        # "MDWD",
        # "MDXG",
        # "MEDP",
        # "MEDS",
        # "MEIP",
        # "MELI",
        # "MEOH",
        # "MERC",
        # "MESO",
        # "MFH",
        # "MFIN",
        # "MGI",
        # "MGIC",
        # "MGNI",
        # "MGPI",
        # "MGRC",
        # "MGYR",
        # "MHLD",
        # "MICT",
        # "MIDD",
        # "MILN",
        # "MIME",
        # "MIND",
        # "MINDP",
        # "MITK",
        # "MKSI",
        # "MKTX",
        # "MLAB",
        # "MLCO",
        # "MLKN",
        # "MLVF",
        # "MMAT",
        # "MMSI",
        # "MMYT",
        # "MNDO",
        # "MNDT",
        # "MNKD",
        # "MNMD",
        # "MNOV",
        # "MNRO",
        # "MNSB",
        # "MNST",
        # "MNTX",
        # "MODV",
        # "MOFG",
        # "MOMO",
        # "MORN",
        # "MOXC",
        # "MPAA",
        # "MRAM",
        # "MRBK",
        # "MRCC",
        # "MRCY",
        # "MRIN",
        # "MRKR",
        # "MRLN",
        # "MRNS",
        # "MRSN",
        # "MRTX",
        # "MRUS",
        # "MRVL",
        # "MSEX",
        # "MSFT",
        # "MSTR",
        # "MSVB",
        # "MTBC",
        # "MTBCP",
        # "MTCH",
        # "MTEM",
        # "MTEX",
        # "MTLS",
        # "MTP",
        # "MTRX",
        # "MTSI",
        # "MU",
        # "MULN",
        # "MVBF",
        # "MVIS",
        # "MYGN",
        # "MYMD",
        # "MYRG",
        # "MYSZ",
        # "NAII",
        # "NAKD",
        # "NAOV",
        # "NATH",
        # "NATI",
        # "NATR",
        # "NAVI",
        # "NBEV",
        # "NBIX",
        # "NBN",
        # "NBRV",
        # "NBSE",
        # "NCBS",
        # "NCMI",
        # "NCNA",
        # "NCTY",
        # "NDAQ",
        # "NDLS",
        # "NDRA",
        # "NDSN",
        # "NEGG",
        # "NEO",
        # "NEOG",
        # "NEON",
        # "NEPH",
        # "NEPT",
        # "NERV",
        # "NESR",
        # "NEWT",
        # "NEXT",
        # "NFBK",
        # "NFLX",
        # "NFTY",
        # "NH",
        # "NHTC",
        # "NICE",
        # "NICK",
        # "NISN",
        # "NKSH",
        # "NKTR",
        # "NLOK",
        # "NLTX",
        # "NMFC",
        # "NMIH",
        # "NMRK",
        # "NMTR",
        # "NNDM",
        # "NODK",
        # "NOTV",
        # "NOVN",
        # "NRBO",
        # "NRC",
        # "NRIM",
        # "NSEC",
        # "NSIT",
        # "NSPR",
        # "NSSC",
        # "NSTG",
        # "NSYS",
        # "NTAP",
        # "NTCT",
        # "NTES",
        # "NTGR",
        # "NTIC",
        # "NTLA",
        # "NTNX",
        # "NTRA",
        # "NTRS",
        # "NTWK",
        # "NUAN",
        # "NURO",
        # "NUVA",
        # "NUWE",
        # "NVAX",
        # "NVCN",
        # "NVCR",
        # "NVDA",
        # "NVEC",
        # "NVEE",
        # "NVFY",
        # "NVIV",
        # "NVMI",
        # "NWBI",
        # "NWE",
        # "NWFL",
        # "NWL",
        # "NWLI",
        # "NWPX",
        # "NWS",
        # "NWSA",
        # "NXGN",
        # "NXPI",
        # "NXST",
        # "NXTD",
        # "NXTG",
        # "NXTP",
        # "NYMT",
        # "NYMTN",
        # "NYMX",
        # "OAS",
        # "OBAS",
        # "OBCI",
        # "OBLG",
        # "OBSV",
        # "OCC",
        # "OCFC",
        # "OCGN",
        # "OCUL",
        # "OCUP",
        # "OCX",
        # "GLPI",
        # "GLRE",
        # "GLYC",
        # "GMAB",
        # "GMBL",
        # "GNCA",
        # "GNSS",
        # "GNTX",
        # "GNTY",
        # "GNUS",
        # "GOGL",
        # "GOGO",
        # "GOOD",
        # "GOOG",
        # "GOOGL",
        # "GPP",
        # "GPRE",
        # "GPRO",
        # "ODFL",
        # "ODP",
        # "ODT",
        # "OEG",
        # "OESX",
        # "OFED",
        # "OFIX",
        # "OFLX",
        # "OFS",
        # "OIIM",
        # "OKTA",
        # "OLB",
        # "OLED",
        # "OLLI",
        # "OMAB",
        # "OMCL",
        # "OMER",
        # "OMEX",
        # "OMP",
        # "OMQS",
        # "ON",
        # "ONB",
        # "ONCS",
        # "ONCT",
        # "ONCY",
        # "ONEQ",
        # "ONTX",
        # "ONVO",
        # "OPBK",
        # "OPCH",
        # "OPGN",
        # "OPHC",
        # "OPK",
        # "OPNT",
        # "OPOF",
        # "OPRX",
        # "OPTN",
        # "ORGO",
        # "ORGS",
        # "ORLY",
        # "ORMP",
        # "ORRF",
        # "OSAT",
        # "OSBC",
        # "OSIS",
        # "OSPN",
        # "OSTK",
        # "OSUR",
        # "OSW",
        # "OTEX",
        # "OTIC",
        # "OTLK",
        # "OTRK",
        # "OTTR",
        # "OVBC",
        # "OVID",
        # "OVLY",
        # "OXBR",
        # "OXLC",
        # "OXLCM",
        # "OXSQ",
        # "OZK",
        # "PAA",
        # "PAAS",
        # "PACB",
        # "PACW",
        # "PAGP",
        # "PAHC",
        # "PALI",
        # "PALT",
        # "PANL",
        # "PANW",
        # "PATI",
        # "PATK",
        # "PAVM",
        # "PAYS",
        # "PAYX",
        # "PBCT",
        # "PBCTP",
        # "PBHC",
        # "PBIP",
        # "PBLA",
        # "PBPB",
        # "PBYI",
        # "PCAR",
        # "PCH",
        # "PCOM",
        # "PCRX",
        # "PCSB",
        # "PCTI",
        # "PCTY",
        # "PCYG",
        # "PCYO",
        # "PDBC",
        # "PDCE",
        # "PDCO",
        # "PDEX",
        # "PDFS",
        # "PDLB",
        # "PDP",
        # "PDSB",
        # "PEBK",
        # "PEBO",
        # "PEGA",
        # "PENN",
        # "PEP",
        # "PERI",
        # "PESI",
        # "PETQ",
        # "PETS",
        # "PETV",
        # "PETZ",
        # "PEY",
        # "PEZ",
        # "PFBC",
        # "PFC",
        # "PFF",
        # "PFG",
        # "PFI",
        # "PFIE",
        # "PFIN",
        # "PFIS",
        # "PFLT",
        # "PFM",
        # "PFMT",
        # "PFSW",
        # "PFX",
        # "PGC",
        # "PGEN",
        # "PGJ",
        # "PHIO",
        # "PHO",
        # "PHUN",
        # "PI",
        # "PID",
        # "PIE",
        # "PINC",
        # "PIO",
        # "PIRS",
        # "PIXY",
        # "PIZ",
        # "PKBK",
        # "PKOH",
        # "PKW",
        # "PLAB",
        # "PLAY",
        # "PLBC",
        # "PLCE",
        # "PLPC",
        # "PLSE",
        # "PLUG",
        # "PLUS",
        # "PLW",
        # "PLXP",
        # "PLXS",
        # "PLYA",
        # "PMCB",
        # "PMD",
        # "PME",
        # "PMTS",
        # "PNBK",
        # "PNFP",
        # "PNNT",
        # "PNQI",
        # "PNRG",
        # "POAI",
        # "PODD",
        # "POLA",
        # "POOL",
        # "POWI",
        # "POWL",
        # "POWW",
        # "PPBI",
        # "PPBT",
        # "PPC",
        # "PPH",
        # "PPSI",
        # "PRAA",
        # "PRDO",
        # "PRFT",
        # "PRFZ",
        # "PRGS",
        # "PRIM",
        # "PROV",
        # "PRPH",
        # "PRPO",
        # "PRQR",
        # "PRTA",
        # "PRTG",
        # "PRTK",
        # "PRTS",
        # "PSC",
        # "PSCC",
        # "PSCD",
        # "PSCE",
        # "PSCF",
        # "PSCH",
        # "PSCI",
        # "PSCM",
        # "PSCT",
        # "PSCU",
        # "PSEC",
        # "PSET",
        # "PSHG",
        # "PSL",
        # "PSMT",
        # "PSTI",
        # "PSTV",
        # "PTC",
        # "PTCT",
        # "PTE",
        # "PTEN",
        # "PTF",
        # "PTGX",
        # "PTH",
        # "PTMN",
        # "PTNR",
        # "PTRS",
        # "PTSI",
        # "PUI",
        # "PVBC",
        # "PWFL",
        # "PWOD",
        # "PXI",
        # "PXLW",
        # "PXS",
        # "PY",
        # "PYPL",
        # "PYR",
        # "PYZ",
        # "PZZA",
        # "QABA",
        # "QAT",
        # "QCLN",
        # "QCOM",
        # "QCRH",
        # "QDEL",
        # "QIPT",
        # "QIWI",
        # "QLGN",
        # "QLYS",
        # "QMCO",
        # "QNRX",
        # "QNST",
        # "QQEW",
        # "QQQ",
        # "QQQX",
        # "QQXT",
        # "QRHC",
        # "QRTEA",
        # "QRTEB",
        # "QRVO",
        # "QTEC",
        # "QTNT",
        # "QTRX",
        # "QUBT",
        # "QUIK",
        # "QUMU",
        # "QURE",
        # "QYLD",
        # "RADA",
        # "RAIL",
        # "RAND",
        # "RARE",
        # "RAVE",
        # "RBB",
        # "RBBN",
        # "RBCAA",
        # "RBCN",
        # "RCEL",
        # "RCII",
        # "RCKT",
        # "RCKY",
        # "RCM",
        # "RCMT",
        # "RCON",
        # "RCRT",
        # "RDCM",
        # "RDFN",
        # "RDHL",
        # "RDI",
        # "RDIB",
        # "RDNT",
        # "RDUS",
        # "RDWR",
        # "REDU",
        # "REED",
        # "REFR",
        # "REG",
        # "REGI",
        # "REGN",
        # "REKR",
        # "RELL",
        # "REPH",
        # "RESN",
        # "RETA",
        # "RETO",
        # "RFDI",
        # "RFEM",
        # "RFEU",
        # "RFIL",
        # "RGCO",
        # "RGEN",
        # "RGLD",
        # "RGLS",
        # "RGNX",
        # "RGP",
        # "RIBT",
        # "RICK",
        # "RIGL",
        # "RILY",
        # "RING",
        # "RIOT",
        # "RKDA",
        # "RLMD",
        # "RMBS",
        # "RMCF",
        # "RMNI",
        # "RMR",
        # "RMTI",
        # "RNDB",
        # "RNDM",
        # "RNDV",
        # "RNEM",
        # "RNLC",
        # "RNMC",
        # "RNRG",
        # "RNSC",
        # "RNST",
        # "RNWK",
        # "ROCC",
        # "ROCK",
        # "ROIC",
        # "ROKU",
        # "ROLL",
        # "ROST",
        # "RPD",
        # "RRGB",
        # "RRR",
        # "RSLS",
        # "RSSS",
        # "RTH",
        # "RUN",
        # "RUSHA",
        # "RUSHB",
        # "RUTH",
        # "RVNC",
        # "RVSB",
        # "RWLK",
        # "RYAAY",
        # "RYTM",
        # "RZLT",
        # "SABR",
        # "SAFM",
        # "SAFT",
        # "SAGE",
        # "SAIA",
        # "SAL",
        # "SALM",
        # "SAMG",
        # "SANM",
        # "SANW",
        # "SASR",
        # "SATS",
        # "SAVA",
        # "SBAC",
        # "SBCF",
        # "SBET",
        # "SBFG",
        # "SBGI",
        # "SBLK",
        # "SBNY",
        # "SBRA",
        # "SBSI",
        # "SBT",
        # "SBUX",
        # "SCHL",
        # "SCHN",
        # "SCKT",
        # "SCOR",
        # "SCPH",
        # "SCSC",
        # "SCVL",
        # "SCWX",
        # "SCYX",
        # "SCZ",
        # "SDG",
        # "SDVY",
        # "SECO",
        # "SEDG",
        # "SEED",
        # "SEEL",
        # "SEIC",
        # "SELB",
        # "SELF",
        # "SENEA",
        # "SESN",
        # "SEVN",
        # "SFBC",
        # "SFIX",
        # "SFM",
        # "SFNC",
        # "SFST",
        # "SGA",
        # "SGBX",
        # "SGC",
        # "SGEN",
        # "SGH",
        # "SGLB",
        # "SGMA",
        # "SGMO",
        # "SGMS",
        # "SGRP",
        # "SGRY",
        # "SHBI",
        # "SHEN",
        # "SHIP",
        # "SHOO",
        # "SHV",
        # "SHY",
        # "SHYF",
        # "SIEB",
        # "SIEN",
        # "SIFY",
        # "SIGA",
        # "SIGI",
        # "SILC",
        # "SIMO",
        # "SINO",
        # "SINT",
        # "SIOX",
        # "SISI",
        # "SIVB",
        # "SKOR",
        # "SKYW",
        # "SKYY",
        # "SLAB",
        # "SLGN",
        # "SLM",
        # "SLMBP",
        # "SLNG",
        # "SLNH",
        # "SLNO",
        # "SLP",
        # "SLQD",
        # "SLRC",
        # "SLRX",
        # "SLS",
        # "SLVO",
        # "SMBC",
        # "SMBK",
        # "SMCI",
        # "SMCP",
        # "SMED",
        # "SMH",
        # "SMID",
        # "SMIT",
        # "SMLR",
        # "SMMF",
        # "SMMT",
        # "SMPL",
        # "SMSI",
        # "SMTC",
        # "SMTI",
        # "SNBR",
        # "SNCR",
        # "SND",
        # "SNDX",
        # "SNES",
        # "SNEX",
        # "SNFCA",
        # "SNGX",
        # "SNLN",
        # "SNOA",
        # "SNPS",
        # "SNSR",
        # "SNT",
        # "SNY",
        # "SOCL",
        # "SOHO",
        # "SOHOB",
        # "SOHOO",
        # "SOHU",
        # "SONN",
        # "SOTK",
        # "SOXX",
        # "SP",
        # "SPCB",
        # "SPI",
        # "SPLK",
        # "SPNE",
        # "SPNS",
        # "SPOK",
        # "SPPI",
        # "SPRO",
        # "SPSC",
        # "SPTN",
        # "SPWH",
        # "SPWR",
        # "SQLV",
        # "SQQQ",
        # "SRAX",
        # "SRCE",
        # "SRCL",
        # "SRDX",
        # "SRET",
        # "SREV",
        # "SRGA",
        # "SRNE",
        # "SRPT",
        # "SRRA",
        # "SRTS",
        # "SSB",
        # "SSBI",
        # "SSKN",
        # "SSNC",
        # "SSNT",
        # "SSP",
        # "SSSS",
        # "SSTI",
        # "SSYS",
        # "STAA",
        # "STAB",
        # "STAF",
        # "STBA",
        # "STCN",
        # "STFC",
        # "STGW",
        # "STKL",
        # "STKS",
        # "STLD",
        # "STRA",
        # "STRL",
        # "STRS",
        # "STRT",
        # "STX",
        # "SUMR",
        # "SUNS",
        # "SUNW",
        # "SUPN",
        # "SUSB",
        # "SUSC",
        # "SVC",
        # "SVRA",
        # "SVVC",
        # "SWBI",
        # "SWIR",
        # "SWKS",
        # "SYBT",
        # "SYBX",
        # "SYNA",
        # "SYNH",
        # "SYNL",
        # "SYPR",
        # "SYRS",
        # "TA",
        # "TACO",
        # "TACT",
        # "TAIT",
        # "TANH",
        # "TANNI",
        # "TANNL",
        # "TANNZ",
        # "TAOP",
        # "TARA",
        # "TAST",
        # "TATT",
        # "TAYD",
        # "TBBK",
        # "TBK",
        # "TBNK",
        # "TBPH",
        # "TCBI",
        # "TCBK",
        # "TCFC",
        # "TCMD",
        # "TCOM",
        # "TCON",
        # "TCPC",
        # "TCX",
        # "TDIV",
        # "TEAM",
        # "TECH",
        # "TEDU",
        # "TENX",
        # "TER",
        # "TESS",
        # "TFSL",
        # "TGA",
        # "TGLS",
        # "TGTX",
        # "THFF",
        # "THMO",
        # "THRM",
        # "THTX",
        # "TILE",
        # "TIPT",
        # "TITN",
        # "TLT",
        # "TMDI",
        # "TMUS",
        # "TNDM",
        # "TNXP",
        # "TOMZ",
        # "TOUR",
        # "TOWN",
        # "TPIC",
        # "TPST",
        # "TQQQ",
        # "TREE",
        # "TRHC",
        # "TRIB",
        # "TRIP",
        # "TRMB",
        # "TRMK",
        # "TRNS",
        # "TROW",
        # "TRS",
        # "TRST",
        # "TRUE",
        # "TRUP",
        # "TRVG",
        # "TRVN",
        # "TSBK",
        # "TSC",
        # "TSCO",
        # "TSEM",
        # "TSLA",
        # "TSRI",
        # "TTD",
        # "TTEC",
        # "TTEK",
        # "TTGT",
        # "TTMI",
        # "TTNP",
        # "TTOO",
        # "TTSH",
        # "TTWO",
        # "TUR",
        # "TURN",
        # "TUSA",
        # "TUSK",
        # "TVTX",
        # "TVTY",
        # "TWIN",
        # "TWNK",
        # "TWOU",
        # "TXMD",
        # "TXN",
        # "TXRH",
        # "TYME",
        # "TZOO",
        # "UAL",
        # "UBCP",
        # "UBFO",
        # "UBOH",
        # "UBSI",
        # "UCBI",
        # "UCTT",
        # "UEIC",
        # "UEPS",
        # "UFCS",
        # "UFPI",
        # "UFPT",
        # "UG",
        # "UHAL",
        # "UIHC",
        # "ULBI",
        # "ULH",
        # "ULTA",
        # "UMBF",
        # "UMPQ",
        # "UNAM",
        # "UNB",
        # "UNIT",
        # "UNTY",
        # "UONE",
        # "UONEK",
        # "UPLD",
        # "URBN",
        # "URGN",
        # "USAK",
        # "USAP",
        # "USAU",
        # "USEG",
        # "USIG",
        # "USIO",
        # "USLB",
        # "USLM",
        # "USMC",
        # "UTHR",
        # "UTMD",
        # "UTSI",
        # "UVSP",
        # "VABK",
        # "VALU",
        # "VBIV",
        # "VBLT",
        # "VBTX",
        # "VC",
        # "VCEL",
        # "VCIT",
        # "VCLT",
        # "VCSH",
        # "VCYT",
        # "VECO",
        # "VEON",
        # "VERB",
        # "VERI",
        # "VERO",
        # "VERU",
        # "VEV",
        # "VG",
        # "VGIT",
        # "VGLT",
        # "VGSH",
        # "VIA",
        # "VIAC",
        # "VIASP",
        # "VIAV",
        # "VICR",
        # "VIGI",
        # "VIRC",
        # "VIRT",
        # "VIRX",
        # "VISL",
        # "VIVE",
        # "VIVO",
        # "VJET",
        # "VKTX",
        # "VQS",
        # "VREX",
        # "VRME",
        # "VRNA",
        # "VRNS",
        # "VRNT",
        # "VRRM",
        # "VSAT",
        # "VSEC",
        # "VSMV",
        # "VSTM",
        # "VTC",
        # "VTGN",
        # "VTHR",
        # "VTNR",
        # "VTSI",
        # "VTWG",
        # "VTWV",
        # "VUZI",
        # "VWOB",
        # "VWTR",
        # "VXRT",
        # "VXUS",
        # "WATT",
        # "WBA",
        # "WDAY",
        # "WDC",
        # "WEN",
        # "WERN",
        # "WETF",
        # "WFCF",
        # "WHF",
        # "WHLM",
        # "WHLR",
        # "WHLRD",
        # "WINT",
        # "WIRE",
        # "WKHS",
        # "WLDN",
        # "WNEB",
        # "WPRT",
        # "WSBC",
        # "WSBF",
        # "WSC",
        # "WSFS",
        # "WTBA",
        # "WTER",
        # "WTFC",
        # "WTRH",
        # "WVE",
        # "WVFC",
        # "WVVI",
        # "WVVIP",
        # "WWD",
        # "WYNN",
        # "XEL",
        # "XELB",
        # "XENT",
        # "XFOR",
        # "XLNX",
        # "XNCR",
        # "XOMA",
        # "XRAY",
        # "XTLB",
        # "YLDE",
        # "YMTX",
        # "YNDX",
        # "YTRA",
        # "YVR",
        # "YY",
        # "Z",
        # "ZBRA",
        # "ZEAL",
        # "ZION",
        # "ZIONO",
        # "ZKIN",
        # "ZNGA",
        # "ZSAN",
        # "ZUMZ",
        # "ZYNE",
        # "ZYXI",
    ]

    all_trades.objects.all().delete()

    # for each in allStockNames:

    #     # utiliites.runTradingBot(request, each)
    #     utiliites.runOnLoop(request, each)



    # return HttpResponse("Run Trades")

    start = time.time()

    currentPosition = 0

    oneMinuteTimer = 59

    while True:

        currentPosition += 1

        oneMinuteTimer += 1

        if oneMinuteTimer == 60:

            print("60 seceonds have passed")

            oneMinuteTimer = 0

            isEnd = utiliites.runOnLoop(request, allStockNames, currentPosition)

            if isEnd == True:

                currentPosition = 0

        
        from access_trades.views import seperate_trades_by_bc, get_peformances_bc
        
        all_trades_ = all_trades.objects.all()
        seperated_trades = seperate_trades_by_bc(all_trades_)
        get_peformances_bc(seperated_trades)

        print("One Minute Timer: ", oneMinuteTimer)

        time.sleep(1)






























































# @csrf_exempt
# def getSingleStockCandles(request):

#     # ipdb.set_trace()
#     """
#     Retrieves stock data for a single ticker and runs a data processing script on the data.

#     Args:
#         request: A Django request object.

#     Returns:
#         An HTTP response confirming the function ran successfully.
#     """

#     # Step 2: Clear out old data
#     all_trades.objects.all().delete()

#     # Step 3: Start timer
#     start = time.time()

#     # Step 4: Run data processing script
#     utiliites.runTradingBot(request, 'AAPL')


#     from access_trades.views import seperate_trades_by_bc, get_peformances_bc
    
#     all_trades_ = all_trades.objects.all()
#     seperated_trades = seperate_trades_by_bc(all_trades_)
#     get_peformances_bc(seperated_trades)


#     # Step 5: Stop timer and calculate run time
#     end = time.time()

#     total_time = end - start

#     # Step 6: Print run time to console
#     print("\nScript Run Time: " + str(total_time) + '\n')

#     # Step 7: Return HTTP response
#     return HttpResponse('Hello BackEnd')
