# Generated by Django 4.0.2 on 2022-04-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('open', models.FloatField(max_length=255, verbose_name='Open')),
                ('close', models.FloatField(max_length=255, verbose_name='Close')),
                ('high', models.FloatField(max_length=255, verbose_name='High')),
                ('low', models.FloatField(max_length=255, verbose_name='Low')),
                ('adjClose', models.FloatField(max_length=255, verbose_name='Adj Close')),
                ('volume', models.FloatField(max_length=255, verbose_name='Volume')),
            ],
        ),
        migrations.CreateModel(
            name='strategyResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=255, verbose_name='stock')),
                ('total_open', models.CharField(max_length=255, verbose_name='total_open')),
                ('total_close', models.CharField(max_length=255, verbose_name='total_close')),
                ('total_won', models.CharField(max_length=255, verbose_name='total_won')),
                ('total_lost', models.CharField(max_length=255, verbose_name='total_lost')),
                ('pnl', models.CharField(max_length=255, verbose_name='pnl')),
                ('strike_rate', models.CharField(max_length=255, verbose_name='strike_rate')),
            ],
        ),
        migrations.CreateModel(
            name='strategySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.CharField(max_length=255, verbose_name='length')),
                ('lowrestriction', models.CharField(max_length=255, verbose_name='low restriction')),
                ('stock', models.CharField(max_length=255, verbose_name='stock')),
            ],
        ),
        migrations.CreateModel(
            name='tradeResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeid', models.CharField(max_length=255, verbose_name='tradeid')),
                ('date_of_pivot_high', models.CharField(max_length=255, verbose_name='low date_of_pivot_high')),
                ('date_of_pivot_low', models.CharField(max_length=255, verbose_name='date_of_pivot_low')),
                ('price_of_pivot_high', models.CharField(max_length=255, verbose_name='price_of_pivot_high')),
                ('price_of_pivot_low', models.CharField(max_length=255, verbose_name='price_of_pivot_low')),
                ('days_between_pivots', models.CharField(max_length=255, verbose_name='days_between_pivots')),
                ('price_pivot_high_snr_tested', models.CharField(max_length=255, verbose_name='price_pivot_high_snr_tested')),
                ('date_pivot_high_snr_tested', models.CharField(max_length=255, verbose_name='date_pivot_high_snr_tested')),
                ('date_entered_short', models.CharField(max_length=255, verbose_name='date_entered_short')),
            ],
        ),
    ]
