# Generated by Django 4.0.2 on 2022-04-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyresults',
            name='length',
            field=models.CharField(default=1, max_length=255, verbose_name='total_open'),
            preserve_default=False,
        ),
    ]
