# Generated by Django 4.0.2 on 2022-04-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_strategyresults_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderesults',
            name='date_of_pivot_high',
        ),
        migrations.RemoveField(
            model_name='traderesults',
            name='date_of_pivot_low',
        ),
        migrations.AddField(
            model_name='traderesults',
            name='cash_invested',
            field=models.CharField(default=-1, max_length=255, verbose_name='cash_invested'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traderesults',
            name='current_cash_in_hand',
            field=models.CharField(default=-1.0, max_length=255, verbose_name='low current_cash_in_hand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traderesults',
            name='date_closed_short',
            field=models.CharField(default=1, max_length=255, verbose_name='date_closed_short'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traderesults',
            name='high_close_mark',
            field=models.CharField(default=1, max_length=255, verbose_name='high_close_mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traderesults',
            name='highest_price_went',
            field=models.CharField(default=1, max_length=255, verbose_name='highest_price_went'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traderesults',
            name='low_close_mark',
            field=models.CharField(default=1, max_length=255, verbose_name='low_close_mark'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traderesults',
            name='lowest_price_went',
            field=models.CharField(default=1, max_length=255, verbose_name='lowest_price_went'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traderesults',
            name='pair_range',
            field=models.CharField(default=1, max_length=255, verbose_name='pair_range'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traderesults',
            name='pivot_pair',
            field=models.CharField(default=1, max_length=255, verbose_name='pivot_pair'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traderesults',
            name='pnl',
            field=models.CharField(default=1, max_length=255, verbose_name='pnl'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traderesults',
            name='price_closed_short',
            field=models.CharField(default=1, max_length=255, verbose_name='price_closed_short'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traderesults',
            name='price_entered_short',
            field=models.CharField(default=1, max_length=255, verbose_name='price_entered_short'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traderesults',
            name='shares_purchased',
            field=models.CharField(default=1, max_length=255, verbose_name='low shares_purchased'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traderesults',
            name='trade_complete',
            field=models.CharField(default=1, max_length=255, verbose_name='low trade_complete'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traderesults',
            name='trade_result',
            field=models.CharField(default=1, max_length=255, verbose_name='trade_result'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traderesults',
            name='trades_active',
            field=models.CharField(default=1, max_length=255, verbose_name='trades_active'),
            preserve_default=False,
        ),
    ]
