# Generated by Django 4.0.2 on 2022-04-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_traderesults_date_of_pivot_high_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderesults',
            name='days_between_pivots',
        ),
        migrations.AlterField(
            model_name='traderesults',
            name='shares_purchased',
            field=models.CharField(max_length=255, verbose_name='shares_purchased'),
        ),
        migrations.AlterField(
            model_name='traderesults',
            name='trade_complete',
            field=models.CharField(max_length=255, verbose_name='trade_complete'),
        ),
    ]
