# Generated by Django 4.0.2 on 2022-04-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_stock_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderesults',
            name='date_of_pivot_high',
            field=models.CharField(default=1, max_length=255, verbose_name='date_of_pivot_high'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traderesults',
            name='date_of_pivot_low',
            field=models.CharField(default=1, max_length=255, verbose_name='date_of_pivot_low'),
            preserve_default=False,
        ),
    ]
