# Generated by Django 4.0.2 on 2022-05-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_traderesults_date_of_pivot_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderesults',
            name='image',
            field=models.CharField(default=1, max_length=255, verbose_name='trades_active'),
            preserve_default=False,
        ),
    ]
