# Generated by Django 4.0.2 on 2022-05-01 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_traderesults_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderesults',
            name='image',
        ),
    ]
