# Generated by Django 4.0.2 on 2022-05-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_remove_traderesults_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderesults',
            name='trades_active',
        ),
        migrations.AddField(
            model_name='traderesults',
            name='image',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
