# Generated by Django 4.0.2 on 2022-05-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_traderesults_image_alter_chartimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderesults',
            name='price_pivot_high_snr_tested',
        ),
    ]
