# Generated by Django 4.0.2 on 2022-05-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_remove_traderesults_price_pivot_high_snr_tested'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderesults',
            name='price_pivot_high_snr_tested',
            field=models.CharField(default=1, max_length=255, verbose_name='price_pivot_high_snr_tested'),
            preserve_default=False,
        ),
    ]
