# Generated by Django 4.0.2 on 2022-05-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_remove_traderesults_cash_invested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderesults',
            name='stock',
            field=models.CharField(default=1, max_length=255, verbose_name='stock'),
            preserve_default=False,
        ),
    ]
