# Generated by Django 4.0.2 on 2022-05-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_traderesults_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyresults',
            name='active',
            field=models.CharField(default=1, max_length=255, verbose_name='active'),
            preserve_default=False,
        ),
    ]
