# Generated by Django 4.0.2 on 2022-05-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_strategyresults_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='totalResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalOpen', models.CharField(max_length=255, verbose_name='totalOpen')),
                ('totalClosed', models.CharField(max_length=255, verbose_name='totalClosed')),
                ('totalWon', models.CharField(max_length=255, verbose_name='totalWon')),
                ('totalLost', models.CharField(max_length=255, verbose_name='totalLost')),
                ('totalPnl', models.CharField(max_length=255, verbose_name='totalPnl')),
                ('totalWr', models.CharField(max_length=255, verbose_name='totalWr')),
            ],
        ),
    ]
