# Generated by Django 4.0.2 on 2022-06-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_totalresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalresults',
            name='avgLost',
            field=models.CharField(default=1, max_length=255, verbose_name='avgLost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totalresults',
            name='avgWin',
            field=models.CharField(default=1, max_length=255, verbose_name='avgWin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totalresults',
            name='largestLost',
            field=models.CharField(default=1, max_length=255, verbose_name='largestLost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totalresults',
            name='largestWin',
            field=models.CharField(default=1, max_length=255, verbose_name='largestWin'),
            preserve_default=False,
        ),
    ]
