# Generated by Django 4.0.2 on 2022-06-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_totalresults_avglost_totalresults_avgwin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='stocksTested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=255, verbose_name='stockTested')),
            ],
        ),
    ]
