# Generated by Django 4.0.2 on 2022-06-18 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0020_savedlists_alter_stockstested_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderesults',
            name='image',
        ),
    ]
