# Generated by Django 4.0.2 on 2022-06-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0021_remove_traderesults_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='chartGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/images/')),
            ],
        ),
    ]
