# Generated by Django 4.0.2 on 2022-07-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_chartgraph'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=255, verbose_name='stock')),
                ('totalPnl', models.CharField(max_length=255, verbose_name='totalPnl')),
                ('avgPnl', models.CharField(max_length=255, verbose_name='avgPnl')),
                ('largestWin', models.CharField(max_length=255, verbose_name='largestWin')),
                ('largestLost', models.CharField(max_length=255, verbose_name='largestLost')),
                ('avgWin', models.CharField(max_length=255, verbose_name='avgWin')),
                ('avgLost', models.CharField(max_length=255, verbose_name='avgLost')),
                ('longestTrade', models.CharField(max_length=255, verbose_name='longestTrade')),
                ('shortestTrade', models.CharField(max_length=255, verbose_name='shortestTrade')),
                ('avgTrade', models.CharField(max_length=255, verbose_name='avgTrade')),
            ],
        ),
        migrations.DeleteModel(
            name='chartGraph',
        ),
    ]
