# Generated by Django 4.0.2 on 2022-07-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0023_stockstatistics_delete_chartgraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalresults',
            name='tested',
            field=models.CharField(default=1, max_length=255, verbose_name='tested'),
            preserve_default=False,
        ),
    ]
