# Generated by Django 4.0.2 on 2022-07-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0024_totalresults_tested'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalresults',
            name='avgTrade',
            field=models.CharField(default=1, max_length=255, verbose_name='avgTrade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totalresults',
            name='longestTrade',
            field=models.CharField(default=1, max_length=255, verbose_name='longestTrade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totalresults',
            name='shortestTrade',
            field=models.CharField(default=1, max_length=255, verbose_name='shortestTrade'),
            preserve_default=False,
        ),
    ]
