# Generated by Django 4.0.2 on 2022-07-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0025_totalresults_avgtrade_totalresults_longesttrade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalresults',
            name='avgTrade',
        ),
        migrations.AddField(
            model_name='totalresults',
            name='avgOneToTwo',
            field=models.CharField(default=1, max_length=255, verbose_name='avgOneToTwo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totalresults',
            name='avgTwoToShort',
            field=models.CharField(default=1, max_length=255, verbose_name='avgTwoToShort'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totalresults',
            name='longestOneToTwo',
            field=models.CharField(default=1, max_length=255, verbose_name='longestOneToTwo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totalresults',
            name='longestTwoToShort',
            field=models.CharField(default=1, max_length=255, verbose_name='longestTwoToShort'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totalresults',
            name='shortestOneToTwo',
            field=models.CharField(default=1, max_length=255, verbose_name='shortestOneToTwo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totalresults',
            name='shortestTwoToShort',
            field=models.CharField(default=1, max_length=255, verbose_name='shortestTwoToShort'),
            preserve_default=False,
        ),
    ]
