# Generated by Django 4.0.2 on 2022-07-08 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0027_totalresults_avgtrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyresults',
            name='largestLost',
            field=models.CharField(default=1, max_length=255, verbose_name='largestLost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategyresults',
            name='largestWin',
            field=models.CharField(default=1, max_length=255, verbose_name='largestWin'),
            preserve_default=False,
        ),
    ]
