# Generated by Django 4.0.2 on 2022-08-08 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0028_strategyresults_largestlost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderesults',
            name='date_closed_short',
        ),
        migrations.RemoveField(
            model_name='traderesults',
            name='date_entered_short',
        ),
        migrations.RemoveField(
            model_name='traderesults',
            name='date_of_pivot_high',
        ),
        migrations.RemoveField(
            model_name='traderesults',
            name='date_of_pivot_low',
        ),
        migrations.RemoveField(
            model_name='traderesults',
            name='date_pivot_high_snr_tested',
        ),
        migrations.RemoveField(
            model_name='traderesults',
            name='high_close_mark',
        ),
        migrations.RemoveField(
            model_name='traderesults',
            name='highest_price_went',
        ),
        migrations.RemoveField(
            model_name='traderesults',
            name='low_close_mark',
        ),
        migrations.RemoveField(
            model_name='traderesults',
            name='lowest_price_went',
        ),
        migrations.RemoveField(
            model_name='traderesults',
            name='pair_range',
        ),
        migrations.RemoveField(
            model_name='traderesults',
            name='pivot_pair',
        ),
        migrations.RemoveField(
            model_name='traderesults',
            name='pnl',
        ),
        migrations.RemoveField(
            model_name='traderesults',
            name='price_closed_short',
        ),
        migrations.RemoveField(
            model_name='traderesults',
            name='price_entered_short',
        ),
        migrations.RemoveField(
            model_name='traderesults',
            name='price_of_pivot_high',
        ),
        migrations.RemoveField(
            model_name='traderesults',
            name='price_of_pivot_low',
        ),
        migrations.RemoveField(
            model_name='traderesults',
            name='price_pivot_high_snr_tested',
        ),
        migrations.RemoveField(
            model_name='traderesults',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='traderesults',
            name='trade_complete',
        ),
        migrations.RemoveField(
            model_name='traderesults',
            name='trade_result',
        ),
    ]
