# Generated by Django 4.0.2 on 2022-08-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0030_traderesults_date_closed_short_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderesults',
            name='rsi',
            field=models.CharField(default=1, max_length=255, verbose_name='rsi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traderesults',
            name='trades_active',
            field=models.CharField(default=1, max_length=255, verbose_name='trades_active'),
            preserve_default=False,
        ),
    ]
