# Generated by Django 4.0.2 on 2022-08-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0031_traderesults_rsi_traderesults_trades_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderesults',
            name='risk',
            field=models.CharField(default=1, max_length=255, verbose_name='risk'),
            preserve_default=False,
        ),
    ]
