# Generated by Django 4.0.2 on 2022-08-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0032_traderesults_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderesults',
            name='reward',
            field=models.CharField(default=1, max_length=255, verbose_name='reward'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traderesults',
            name='riskRewardRatio',
            field=models.CharField(default=1, max_length=255, verbose_name='riskRewardRatio'),
            preserve_default=False,
        ),
    ]
