# Generated by Django 4.0.2 on 2022-08-31 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0033_traderesults_reward_traderesults_riskrewardratio'),
    ]

    operations = [
        migrations.CreateModel(
            name='activeTrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeid', models.CharField(max_length=255, verbose_name='tradeid')),
                ('shares_purchased', models.CharField(max_length=255, verbose_name='shares_purchased')),
                ('date_of_pivot_high', models.CharField(max_length=255, verbose_name='date_of_pivot_high')),
                ('date_of_pivot_low', models.CharField(max_length=255, verbose_name='date_of_pivot_low')),
                ('price_of_pivot_high', models.CharField(max_length=255, verbose_name='price_of_pivot_high')),
                ('price_of_pivot_low', models.CharField(max_length=255, verbose_name='price_of_pivot_low')),
                ('pair_range', models.CharField(max_length=255, verbose_name='pair_range')),
                ('days_between_pivots', models.CharField(max_length=255, verbose_name='days_between_pivots')),
                ('date_pivot_high_snr_tested', models.CharField(max_length=255, verbose_name='date_pivot_high_snr_tested')),
                ('price_pivot_high_snr_tested', models.CharField(max_length=255, verbose_name='price_pivot_high_snr_tested')),
                ('date_entered_short', models.CharField(max_length=255, verbose_name='date_entered_short')),
                ('price_entered_short', models.CharField(max_length=255, verbose_name='price_entered_short')),
                ('high_close_mark', models.CharField(max_length=255, verbose_name='high_close_mark')),
                ('low_close_mark', models.CharField(max_length=255, verbose_name='low_close_mark')),
                ('lowest_price_went', models.CharField(max_length=255, verbose_name='lowest_price_went')),
                ('highest_price_went', models.CharField(max_length=255, verbose_name='highest_price_went')),
                ('pnl', models.CharField(max_length=255, verbose_name='pnl')),
                ('cash_invested', models.CharField(max_length=255, verbose_name='cash_invested')),
                ('current_cash_in_hand', models.CharField(max_length=255, verbose_name='current_cash_in_hand')),
                ('trades_active', models.CharField(max_length=255, verbose_name='trades_active')),
            ],
        ),
    ]
