# Generated by Django 4.0.2 on 2022-08-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0034_activetrades'),
    ]

    operations = [
        migrations.AddField(
            model_name='activetrades',
            name='symbol',
            field=models.CharField(default=1, max_length=255, verbose_name='trades_active'),
            preserve_default=False,
        ),
    ]
