# Generated by Django 4.0.2 on 2022-09-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0035_activetrades_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='activetrades',
            name='activePrice',
            field=models.CharField(default=1, max_length=255, verbose_name='trades_active'),
            preserve_default=False,
        ),
    ]
