# Generated by Django 4.0.2 on 2022-09-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0036_activetrades_activeprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='activetrades',
            name='tradeType',
            field=models.CharField(default=1, max_length=255, verbose_name='tradeType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activetrades',
            name='activePrice',
            field=models.CharField(max_length=255, verbose_name='activePrice'),
        ),
        migrations.AlterField(
            model_name='activetrades',
            name='symbol',
            field=models.CharField(max_length=255, verbose_name='symbol'),
        ),
    ]
