# Generated by Django 4.0.2 on 2022-09-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0037_activetrades_tradetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activetrades',
            name='durationOfTrade',
            field=models.CharField(default=1, max_length=255, verbose_name='tradeType'),
            preserve_default=False,
        ),
    ]
