# Generated by Django 4.0.2 on 2023-06-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='filtered_trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeInfo', models.JSONField(null=True)),
                ('pivotInfo', models.JSONField(null=True)),
                ('settings', models.JSONField(null=True)),
                ('pnl', models.JSONField(null=True)),
                ('retracement', models.JSONField(null=True)),
                ('enterExitInfo', models.JSONField(null=True)),
                ('duration', models.JSONField(null=True)),
                ('movement', models.JSONField(null=True)),
                ('chartData', models.JSONField(null=True)),
            ],
        ),
    ]
