# Generated by Django 4.2.3 on 2023-09-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='peformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retracement', models.JSONField(null=True)),
                ('trades', models.JSONField(null=True)),
                ('wins', models.JSONField(null=True)),
                ('lost', models.JSONField(null=True)),
                ('active', models.JSONField(null=True)),
                ('average_price_dropped', models.JSONField(null=True)),
                ('lowest_price_dropped', models.JSONField(null=True)),
                ('win_pct', models.JSONField(null=True)),
                ('rsi_wr', models.JSONField(null=True)),
                ('volume_change_win_pct', models.JSONField(null=True)),
                ('volume_change_lose_pct', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradesInChartView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeInfo', models.JSONField(null=True)),
                ('pivotInfo', models.JSONField(null=True)),
                ('settings', models.JSONField(null=True)),
                ('pnl', models.JSONField(null=True)),
                ('retracement', models.JSONField(null=True)),
                ('enterExitInfo', models.JSONField(null=True)),
                ('duration', models.JSONField(null=True)),
                ('movement', models.JSONField(null=True)),
                ('chartData', models.JSONField(null=True)),
            ],
        ),
    ]
