# Generated by Django 4.0.2 on 2023-06-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_trades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='peformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_pct', models.CharField(max_length=255, verbose_name='win_pct')),
                ('duration', models.CharField(max_length=255, verbose_name='duration')),
                ('lowest_price_dropped', models.CharField(max_length=255, verbose_name='lowest_price_dropped')),
                ('average_price_dropped', models.CharField(max_length=255, verbose_name='average_price_dropped')),
            ],
        ),
    ]
