# Generated by Django 4.2.3 on 2023-09-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_trades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peformance',
            name='average_length',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='peformance',
            name='average_length_win',
            field=models.JSONField(null=True),
        ),
    ]
