# Generated by Django 4.2.5 on 2023-10-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_trades', '0002_peformance_average_length_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cd_peformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retracement', models.JSONField(null=True)),
                ('trades', models.JSONField(null=True)),
                ('wins', models.JSONField(null=True)),
                ('lost', models.JSONField(null=True)),
                ('active', models.JSONField(null=True)),
                ('average_price_dropped', models.JSONField(null=True)),
                ('lowest_price_dropped', models.JSONField(null=True)),
                ('win_pct', models.JSONField(null=True)),
                ('rsi_wr', models.JSONField(null=True)),
                ('volume_change_win_pct', models.JSONField(null=True)),
                ('volume_change_lose_pct', models.JSONField(null=True)),
                ('average_length_win', models.JSONField(null=True)),
                ('average_length', models.JSONField(null=True)),
            ],
        ),
    ]
