# Generated by Django 4.0.2 on 2023-06-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_trades', '0002_peformance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peformance',
            name='average_price_dropped',
        ),
        migrations.RemoveField(
            model_name='peformance',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='peformance',
            name='lowest_price_dropped',
        ),
        migrations.RemoveField(
            model_name='peformance',
            name='win_pct',
        ),
        migrations.AddField(
            model_name='peformance',
            name='eight',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='peformance',
            name='five',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='peformance',
            name='four',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='peformance',
            name='nine',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='peformance',
            name='one',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='peformance',
            name='seven',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='peformance',
            name='six',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='peformance',
            name='ten',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='peformance',
            name='three',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='peformance',
            name='two',
            field=models.JSONField(null=True),
        ),
    ]
