# Generated by Django 4.2.5 on 2023-10-14 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_trades', '0003_cd_peformance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cd_peformance',
            new_name='cd_pef',
        ),
    ]
