# Generated by Django 4.0.2 on 2023-06-20 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_trades', '0003_remove_peformance_average_price_dropped_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peformance',
            old_name='eight',
            new_name='all_peformances',
        ),
        migrations.RemoveField(
            model_name='peformance',
            name='five',
        ),
        migrations.RemoveField(
            model_name='peformance',
            name='four',
        ),
        migrations.RemoveField(
            model_name='peformance',
            name='nine',
        ),
        migrations.RemoveField(
            model_name='peformance',
            name='one',
        ),
        migrations.RemoveField(
            model_name='peformance',
            name='seven',
        ),
        migrations.RemoveField(
            model_name='peformance',
            name='six',
        ),
        migrations.RemoveField(
            model_name='peformance',
            name='ten',
        ),
        migrations.RemoveField(
            model_name='peformance',
            name='three',
        ),
        migrations.RemoveField(
            model_name='peformance',
            name='two',
        ),
    ]
