# Generated by Django 4.0.2 on 2023-06-21 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_trades', '0004_rename_eight_peformance_all_peformances_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='filtered_trade',
            new_name='trades_in_chart_view',
        ),
    ]
