# Generated by Django 4.0.2 on 2023-07-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_trades', '0006_rename_trades_in_chart_view_tradesinchartview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peformance',
            old_name='all_peformances',
            new_name='active',
        ),
        migrations.AddField(
            model_name='peformance',
            name='average_price_dropped',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='peformance',
            name='lost',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='peformance',
            name='lowest_price_dropped',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='peformance',
            name='retracement',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='peformance',
            name='rsi_wr',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='peformance',
            name='trades',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='peformance',
            name='volume_change_lose_pct',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='peformance',
            name='volume_change_win_pct',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='peformance',
            name='win_pct',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='peformance',
            name='wins',
            field=models.JSONField(null=True),
        ),
    ]
