# Generated by Django 4.2.5 on 2023-11-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_trades', '0006_cd_peformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='by_symbols',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('winpct', models.CharField(max_length=100)),
            ],
        ),
    ]
