# Generated by Django 4.2.5 on 2023-11-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_trades', '0007_by_symbols'),
    ]

    operations = [
        migrations.AddField(
            model_name='by_symbols',
            name='live',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='by_symbols',
            name='lost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='by_symbols',
            name='won',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
