# Generated by Django 4.2.5 on 2023-12-21 06:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('symbol', models.CharField(max_length=100)),
                ('exchange', models.CharField(max_length=100)),
                ('trade_start_date', models.DateField()),
                ('trade_end_date', models.DateField()),
                ('trade_duration', models.IntegerField()),
                ('trade_open', models.BooleanField()),
                ('trade_closed', models.BooleanField()),
                ('trade_market', models.CharField(max_length=100)),
                ('trade_result', models.CharField(max_length=100)),
                ('current_candle_price', models.FloatField()),
                ('current_candle_date', models.DateField()),
                ('lowest_price_dropped', models.FloatField()),
                ('current_candle_rsi', models.FloatField()),
                ('current_candle_volume', models.FloatField()),
                ('risk', models.FloatField()),
                ('reward', models.FloatField()),
                ('stop_loss', models.FloatField()),
                ('take_profit', models.FloatField()),
                ('pnl', models.FloatField()),
                ('return_percentage', models.FloatField()),
                ('risk_reward_ratio', models.IntegerField()),
            ],
        ),
    ]
