# Generated by Django 4.2.5 on 2023-12-29 07:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Trades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Single_A_Pivot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pivot_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('pivot_letter', models.CharField(max_length=100)),
                ('pivot_color', models.CharField(max_length=100)),
                ('pivot_length', models.IntegerField()),
                ('pivot_start_date', models.DateField()),
                ('pivot_date', models.DateField()),
                ('pivot_end_date', models.DateField()),
                ('pivot_open', models.FloatField()),
                ('pivot_high', models.FloatField()),
                ('pivot_close', models.FloatField()),
                ('pivot_low', models.FloatField()),
                ('bars_between_previous_pivot', models.IntegerField()),
                ('days_between_previous_pivot', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='trade',
            name='a_to_b_length_bars',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='a_to_b_length_days',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='b_to_c_length_bars',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='b_to_c_length_days',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='bc_retracement',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='c_to_d_length_bars',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='c_to_d_length_days',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='cd_retracement',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='enter_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='enter_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='exit_date',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='exit_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='current_candle_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='current_candle_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='current_candle_rsi',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='current_candle_volume',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='exchange',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='lowest_price_dropped',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='pnl',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='return_percentage',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='reward',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='risk',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='risk_reward_ratio',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='stop_loss',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='symbol',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='take_profit',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_duration',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_market',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_open',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_result',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
