# Generated by Django 4.2.5 on 2023-12-29 08:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('total_return', models.FloatField()),
                ('total_win_percentage', models.FloatField()),
                ('initial_cash_investment', models.FloatField()),
                ('current_cash_investment', models.FloatField()),
                ('total_trades', models.IntegerField()),
                ('average_trade_duration_days', models.IntegerField()),
            ],
        ),
    ]
