# Generated by Django 4.0.2 on 2022-09-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trades', models.CharField(max_length=255, verbose_name='trades')),
                ('active', models.CharField(max_length=255, verbose_name='active')),
                ('closed', models.CharField(max_length=255, verbose_name='closed')),
                ('wins', models.CharField(max_length=255, verbose_name='wins')),
                ('losses', models.CharField(max_length=255, verbose_name='losses')),
                ('brokeEven', models.CharField(max_length=255, verbose_name='brokeEven')),
                ('winPct', models.CharField(max_length=255, verbose_name='winPct')),
                ('largestWin', models.CharField(max_length=255, verbose_name='largestWin')),
                ('largestLost', models.CharField(max_length=255, verbose_name='largestLost')),
                ('avgWin', models.CharField(max_length=255, verbose_name='avgWin')),
                ('avgLost', models.CharField(max_length=255, verbose_name='avgLost')),
                ('pnl', models.CharField(max_length=255, verbose_name='pnl')),
                ('longs', models.CharField(max_length=255, verbose_name='longs')),
                ('shorts', models.CharField(max_length=255, verbose_name='shorts')),
                ('longWins', models.CharField(max_length=255, verbose_name='longWins')),
                ('shortWins', models.CharField(max_length=255, verbose_name='shortWins')),
                ('longWinPct', models.CharField(max_length=255, verbose_name='tralongWinPctdes')),
                ('shortWinPct', models.CharField(max_length=255, verbose_name='shortWinPct')),
                ('longestTrade', models.CharField(max_length=255, verbose_name='longestTrade')),
                ('shortestTrade', models.CharField(max_length=255, verbose_name='shortestTrade')),
                ('avgTrade', models.CharField(max_length=255, verbose_name='avgTrade')),
                ('avgBull', models.CharField(max_length=255, verbose_name='avgBull')),
                ('avgBear', models.CharField(max_length=255, verbose_name='avgBear')),
                ('highestStrategyPct', models.CharField(max_length=255, verbose_name='highestStrategyPct')),
                ('lowestStrategyPct', models.CharField(max_length=255, verbose_name='lowestStrategyPct')),
            ],
        ),
    ]
