# Generated by Django 4.0.2 on 2022-10-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total_statistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='averageABCDLength',
            field=models.CharField(default=1, max_length=255, verbose_name='averageABCDLength'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='averageAtoBLength',
            field=models.CharField(default=1, max_length=255, verbose_name='averageAtoBLength'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='averageBtoCLength',
            field=models.CharField(default=1, max_length=255, verbose_name='averageBtoCLength'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='averageCtoDLength',
            field=models.CharField(default=1, max_length=255, verbose_name='averageCtoDLength'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='length_AtoB',
            field=models.CharField(default=1, max_length=255, verbose_name='length_AtoB'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='length_AtoD',
            field=models.CharField(default=1, max_length=255, verbose_name='length_AtoD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='length_BtoC',
            field=models.CharField(default=1, max_length=255, verbose_name='length_BtoC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='length_CtoD',
            field=models.CharField(default=1, max_length=255, verbose_name='length_CtoD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longestABCDLength',
            field=models.CharField(default=1, max_length=255, verbose_name='longestABCDLength'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longestAtoBLength',
            field=models.CharField(default=1, max_length=255, verbose_name='longestAtoBLength'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longestBtoCLength',
            field=models.CharField(default=11, max_length=255, verbose_name='longestBtoCLength'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longestCtoDLength',
            field=models.CharField(default=11, max_length=255, verbose_name='longestCtoDLength'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortestABCDLength',
            field=models.CharField(default=1, max_length=255, verbose_name='shortestABCDLength'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortestAtoBLength',
            field=models.CharField(default=1, max_length=255, verbose_name='shortestAtoBLength'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortestBtoCLength',
            field=models.CharField(default=1, max_length=255, verbose_name='shortestBtoCLength'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortestCtoDLength',
            field=models.CharField(default=1, max_length=255, verbose_name='shortestCtoDLength'),
            preserve_default=False,
        ),
    ]
