# Generated by Django 4.0.2 on 2022-10-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total_statistics', '0002_statistics_averageabcdlength_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='averageInvestment',
            field=models.CharField(default=1, max_length=255, verbose_name='averageInvestment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='averageROI',
            field=models.CharField(default=1, max_length=255, verbose_name='averageInvestment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='averageReturn',
            field=models.CharField(default=1, max_length=255, verbose_name='averageInvestment'),
            preserve_default=False,
        ),
    ]
