# Generated by Django 4.0.2 on 2022-10-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total_statistics', '0003_statistics_averageinvestment_statistics_averageroi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='averageRisk',
            field=models.CharField(default=1, max_length=255, verbose_name='averageRisk'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statistics',
            name='averageROI',
            field=models.CharField(max_length=255, verbose_name='averageROI'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='averageReturn',
            field=models.CharField(max_length=255, verbose_name='averageReturn'),
        ),
    ]
