# Generated by Django 4.0.2 on 2022-10-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total_statistics', '0004_statistics_averagerisk_alter_statistics_averageroi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='averageReward',
            field=models.CharField(default=1, max_length=255, verbose_name='averageReward'),
            preserve_default=False,
        ),
    ]
