# Generated by Django 4.0.2 on 2022-10-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total_statistics', '0007_statistics_activepnl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='activeDown',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='activeUp',
        ),
        migrations.AddField(
            model_name='statistics',
            name='activeLosing',
            field=models.CharField(default=1, max_length=255, verbose_name='activeLosing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='activeWinning',
            field=models.CharField(default=1, max_length=255, verbose_name='activeWinning'),
            preserve_default=False,
        ),
    ]
