# Generated by Django 4.0.2 on 2022-10-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total_statistics', '0008_remove_statistics_activedown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='longStarts',
            field=models.CharField(default=11, max_length=255, verbose_name='longStarts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortStarts',
            field=models.CharField(default=1, max_length=255, verbose_name='shortStarts'),
            preserve_default=False,
        ),
    ]
