# Generated by Django 4.0.2 on 2022-10-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total_statistics', '0009_statistics_longstarts_statistics_shortstarts'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='longEnds',
            field=models.CharField(default=1, max_length=255, verbose_name='longEnds'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortEnds',
            field=models.CharField(default=1, max_length=255, verbose_name='shortEnds'),
            preserve_default=False,
        ),
    ]
