# Generated by Django 4.0.2 on 2022-10-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total_statistics', '0010_statistics_longends_statistics_shortends'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='longToLong',
            field=models.CharField(default=1, max_length=255, verbose_name='longToLong'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longToShort',
            field=models.CharField(default=1, max_length=255, verbose_name='longToShort'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortToLong',
            field=models.CharField(default=1, max_length=255, verbose_name='shortToLong'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortToShort',
            field=models.CharField(default=1, max_length=255, verbose_name='shortToShort'),
            preserve_default=False,
        ),
    ]
