# Generated by Django 4.0.2 on 2022-10-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total_statistics', '0011_statistics_longtolong_statistics_longtoshort_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='longStartPNL',
            field=models.CharField(default=1, max_length=255, verbose_name='longStartPNL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longStartWinPct',
            field=models.CharField(default=1, max_length=255, verbose_name='longStartWinPct'),
            preserve_default=False,
        ),
    ]
