# Generated by Django 4.0.2 on 2022-10-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total_statistics', '0012_statistics_longstartpnl_statistics_longstartwinpct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='longStartPNL',
        ),
        migrations.AddField(
            model_name='statistics',
            name='longStartPnl',
            field=models.CharField(default=1, max_length=255, verbose_name='longStartPnl'),
            preserve_default=False,
        ),
    ]
