# Generated by Django 4.0.2 on 2022-10-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total_statistics', '0013_remove_statistics_longstartpnl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='longStartWins',
            field=models.CharField(default=1, max_length=255, verbose_name='longStartWinPct'),
            preserve_default=False,
        ),
    ]
