# Generated by Django 4.0.2 on 2022-10-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total_statistics', '0014_statistics_longstartwins'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='longStartLost',
            field=models.CharField(default=1, max_length=255, verbose_name='longStartLost'),
            preserve_default=False,
        ),
    ]
