# Generated by Django 4.0.2 on 2022-10-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total_statistics', '0015_statistics_longstartlost'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='longEndLost',
            field=models.CharField(default=1, max_length=255, verbose_name='longEndLost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longEndPnl',
            field=models.CharField(default=1, max_length=255, verbose_name='longEndPnl'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longEndWinPct',
            field=models.CharField(default=1, max_length=255, verbose_name='longEndWinPct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longEndWins',
            field=models.CharField(default=1, max_length=255, verbose_name='longEndWins'),
            preserve_default=False,
        ),
    ]
