# Generated by Django 4.0.2 on 2022-10-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total_statistics', '0016_statistics_longendlost_statistics_longendpnl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='shortEndLost',
            field=models.CharField(default=1, max_length=255, verbose_name='shortEndLost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortEndPnl',
            field=models.CharField(default=1, max_length=255, verbose_name='shortEndPnl'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortEndWinPct',
            field=models.CharField(default=1, max_length=255, verbose_name='shortEndWinPct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortEndWins',
            field=models.CharField(default=1, max_length=255, verbose_name='shortEndWins'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortStartLost',
            field=models.CharField(default=1, max_length=255, verbose_name='shortStartLost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortStartPnl',
            field=models.CharField(default=1, max_length=255, verbose_name='shortStartPnl'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortStartWinPct',
            field=models.CharField(default=1, max_length=255, verbose_name='shortStartWinPct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortStartWins',
            field=models.CharField(default=1, max_length=255, verbose_name='shortStartWins'),
            preserve_default=False,
        ),
    ]
