# Generated by Django 4.0.2 on 2022-10-31 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total_statistics', '0019_statistics_longtolonglostcount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='longEndCount',
            field=models.CharField(default=1, max_length=255, verbose_name='longEndCount'),
            preserve_default=False,
        ),
    ]
