# Generated by Django 4.0.2 on 2022-10-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total_statistics', '0021_statistics_longtolongcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='longToShortCount',
            field=models.CharField(default=1, max_length=255, verbose_name='longToShortCount'),
            preserve_default=False,
        ),
    ]
