# Generated by Django 4.0.2 on 2022-10-31 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total_statistics', '0023_statistics_shortendcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='activeWr',
            field=models.CharField(default=1, max_length=255, verbose_name='activeWr'),
            preserve_default=False,
        ),
    ]
