# Generated by Django 4.0.2 on 2022-11-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total_statistics', '0024_statistics_activewr'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='returnPercentage',
            field=models.CharField(default=1, max_length=255, verbose_name='returnPercentage'),
            preserve_default=False,
        ),
    ]
