# Generated by Django 4.0.2 on 2022-11-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total_statistics', '0026_statistics_highestlossreturnpct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='crypto',
            field=models.CharField(default=1, max_length=255, verbose_name='crypto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='forex',
            field=models.CharField(default=1, max_length=255, verbose_name='forex'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='nasdaq',
            field=models.CharField(default=1, max_length=255, verbose_name='nasdaq'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='options',
            field=models.CharField(default=1, max_length=255, verbose_name='options'),
            preserve_default=False,
        ),
    ]
