# Generated by Django 4.0.2 on 2022-11-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total_statistics', '0027_statistics_crypto_statistics_forex_statistics_nasdaq_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='active',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='activeLosing',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='activeWinning',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='averageABCDLength',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='averageAtoBLength',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='averageBtoCLength',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='averageCtoDLength',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='averageROI',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='avgBear',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='avgBull',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='avgTrade',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='brokeEven',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='crypto',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='forex',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='highestLossReturnPct',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='highestStrategyPct',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='highestWinReturnPct',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='length_AtoB',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='length_AtoD',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='length_BtoC',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='length_CtoD',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longEndLost',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longEndWinPct',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longEnds',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longStartLost',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longStartWinPct',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longStartWins',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longStarts',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longToLong',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longToLongWinPct',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longToShort',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longToShortWinPct',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longWins',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longestABCDLength',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longestAtoBLength',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longestBtoCLength',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longestCtoDLength',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longestTrade',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longs',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='lossReturnPercentage',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='lowestLossReturnPct',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='lowestStrategyPct',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='lowestWinReturnPct',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='nasdaq',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='options',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='pnl',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='returnPercentage',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortEndLost',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortEndWinPct',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortEndWins',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortEnds',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortStartLost',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortStartPnl',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortStartWinPct',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortStartWins',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortStarts',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortToLong',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortToLongWinPct',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortToShort',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortToShortWinPct',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortWinPct',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortWins',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortestABCDLength',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortestAtoBLength',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortestBtoCLength',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortestCtoDLength',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortestTrade',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shorts',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='trades',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='winPct',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='wins',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='winsReturnPercentage',
        ),
        migrations.AddField(
            model_name='statistics',
            name='activeLosingCount',
            field=models.CharField(default=1, max_length=255, verbose_name='activeLosingCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='activeTradesCount',
            field=models.CharField(default=1, max_length=255, verbose_name='activeTradesCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='activeWinningCount',
            field=models.CharField(default=1, max_length=255, verbose_name='activeWinningCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='avgAToB',
            field=models.CharField(default=1, max_length=255, verbose_name='avgAToB'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='avgAtoD',
            field=models.CharField(default=1, max_length=255, verbose_name='avgAtoD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='avgBtoC',
            field=models.CharField(default=1, max_length=255, verbose_name='avgBtoC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='avgCtoD',
            field=models.CharField(default=1, max_length=255, verbose_name='avgCtoD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='closedLostCount',
            field=models.CharField(default=1, max_length=255, verbose_name='closedLostCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='closedPnl',
            field=models.CharField(default=1, max_length=255, verbose_name='closedPnl'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='closedRoiPct',
            field=models.CharField(default=1, max_length=255, verbose_name='closedRoiPct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='closedTradesCount',
            field=models.CharField(default=1, max_length=255, verbose_name='closedTradesCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='closedWinCount',
            field=models.CharField(default=1, max_length=255, verbose_name='closedWinCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='closedWr',
            field=models.CharField(default=1, max_length=255, verbose_name='closedWr'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='cryptoCount',
            field=models.CharField(default=1, max_length=255, verbose_name='cryptoCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='forexCount',
            field=models.CharField(default=1, max_length=255, verbose_name='forexCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='largestInvestment',
            field=models.CharField(default=1, max_length=255, verbose_name='largestInvestment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='largestReturn',
            field=models.CharField(default=1, max_length=255, verbose_name='largestReturn'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='largestReward',
            field=models.CharField(default=1, max_length=255, verbose_name='largestReward'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='largestRisk',
            field=models.CharField(default=1, max_length=255, verbose_name='largestRisk'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longEndWr',
            field=models.CharField(default=1, max_length=255, verbose_name='longEndWr'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longEndsCount',
            field=models.CharField(default=1, max_length=255, verbose_name='longEndsCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longEndsLost',
            field=models.CharField(default=1, max_length=255, verbose_name='longEndsLost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longStartCount',
            field=models.CharField(default=1, max_length=255, verbose_name='longStartCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longStartLostCount',
            field=models.CharField(default=1, max_length=255, verbose_name='longStartLostCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longStartWinsCount',
            field=models.CharField(default=1, max_length=255, verbose_name='longStartWinsCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longStartWr',
            field=models.CharField(default=1, max_length=255, verbose_name='longStartWr'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longStartsCount',
            field=models.CharField(default=1, max_length=255, verbose_name='longStartsCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longToLongWr',
            field=models.CharField(default=1, max_length=255, verbose_name='longToLongWr'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longToShortWr',
            field=models.CharField(default=1, max_length=255, verbose_name='longToShortWr'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longestAtoB',
            field=models.CharField(default=1, max_length=255, verbose_name='longestAtoB'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longestAtoD',
            field=models.CharField(default=1, max_length=255, verbose_name='longestAtoD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longestBtoC',
            field=models.CharField(default=1, max_length=255, verbose_name='longestBtoC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longestCtoD',
            field=models.CharField(default=1, max_length=255, verbose_name='longestCtoD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='lossesHighestRoiPct',
            field=models.CharField(default=1, max_length=255, verbose_name='lossesHighestRoiPct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='lossesLowestRoiPct',
            field=models.CharField(default=1, max_length=255, verbose_name='lossesLowestRoiPct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='lossesTotalRoiPct',
            field=models.CharField(default=1, max_length=255, verbose_name='lossesTotalRoiPct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='nasdaqCount',
            field=models.CharField(default=1, max_length=255, verbose_name='nasdaqCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='optionsCount',
            field=models.CharField(default=1, max_length=255, verbose_name='optionsCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortEndLostCount',
            field=models.CharField(default=1, max_length=255, verbose_name='shortEndLostCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortEndWinsCount',
            field=models.CharField(default=1, max_length=255, verbose_name='shortEndWinsCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortEndWr',
            field=models.CharField(default=1, max_length=255, verbose_name='shortEndWr'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortEndsCount',
            field=models.CharField(default=1, max_length=255, verbose_name='shortEndsCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortStartCount',
            field=models.CharField(default=1, max_length=255, verbose_name='shortStartCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortStartLostCount',
            field=models.CharField(default=1, max_length=255, verbose_name='shortStartLostCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortStartWinsCount',
            field=models.CharField(default=1, max_length=255, verbose_name='shortStartWinsCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortStartWr',
            field=models.CharField(default=1, max_length=255, verbose_name='shortStartWr'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortStartsCount',
            field=models.CharField(default=1, max_length=255, verbose_name='shortStartsCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortToLongCount',
            field=models.CharField(default=1, max_length=255, verbose_name='shortToLongCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortToLongWr',
            field=models.CharField(default=1, max_length=255, verbose_name='shortToLongWr'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortToShortCount',
            field=models.CharField(default=1, max_length=255, verbose_name='shortToShortCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortToShortWr',
            field=models.CharField(default=1, max_length=255, verbose_name='shortToShortWr'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortestAtoB',
            field=models.CharField(default=1, max_length=255, verbose_name='shortestAtoB'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortestAtoD',
            field=models.CharField(default=1, max_length=255, verbose_name='shortestAtoD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortestBtoC',
            field=models.CharField(default=1, max_length=255, verbose_name='shortestBtoC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortestCtoD',
            field=models.CharField(default=1, max_length=255, verbose_name='shortestCtoD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='smallestInvestment',
            field=models.CharField(default=1, max_length=255, verbose_name='smallestInvestment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='smallestReturn',
            field=models.CharField(default=1, max_length=255, verbose_name='smallestReturn'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='smallestReward',
            field=models.CharField(default=1, max_length=255, verbose_name='smallestReward'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='smallestRisk',
            field=models.CharField(default=1, max_length=255, verbose_name='smallestRisk'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='totalTradesCount',
            field=models.CharField(default=1, max_length=255, verbose_name='totalTradesCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='winsHighestRoiPct',
            field=models.CharField(default=1, max_length=255, verbose_name='winsHighestRoiPct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='winsTotalRoiPct',
            field=models.CharField(default=1, max_length=255, verbose_name='winsTotalRoiPct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='winslowestRoiPct',
            field=models.CharField(default=1, max_length=255, verbose_name='winslowestRoiPct'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statistics',
            name='longWinPct',
            field=models.CharField(max_length=255, verbose_name='shortStartPnl'),
        ),
    ]
