# Generated by Django 4.0.2 on 2022-11-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total_statistics', '0030_remove_statistics_longendscount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='totalLostCount',
            field=models.CharField(default=1, max_length=255, verbose_name='totalLostCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='totalPnl',
            field=models.CharField(default=1, max_length=255, verbose_name='totalPnl'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='totalWinCount',
            field=models.CharField(default=1, max_length=255, verbose_name='totalWinCount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='totalWr',
            field=models.CharField(default=1, max_length=255, verbose_name='totalWr'),
            preserve_default=False,
        ),
    ]
