# Generated by Django 4.0.2 on 2022-11-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total_statistics', '0031_statistics_totallostcount_statistics_totalpnl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='totalAvgReturn',
            field=models.CharField(default=1, max_length=255, verbose_name='totalAvgReturn'),
            preserve_default=False,
        ),
    ]
