# Generated by Django 4.0.2 on 2022-11-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total_statistics', '0033_remove_statistics_cryptocount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='longEndCount',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longEndPnl',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longEndWins',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longEndWr',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longEndsLost',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longStartCount',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longStartLostCount',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longStartPnl',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longStartWinsCount',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longStartWr',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longToLongCount',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longToLongLostCount',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longToLongPnl',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longToLongWinCount',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longToLongWr',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longToShortCount',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longToShortLostCount',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longToShortPnl',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longToShortWinCount',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longToShortWr',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortEndCount',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortEndLostCount',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortEndPnl',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortEndWinsCount',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortEndWr',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortStartCount',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortStartLostCount',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortStartPnl',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortStartWinsCount',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortStartWr',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortToLongCount',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortToLongLostCount',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortToLongPnl',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortToLongWinCount',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortToLongWr',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortToShortCount',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortToShortLostCount',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortToShortPnl',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortToShortWinCount',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='shortToShortWr',
        ),
        migrations.AddField(
            model_name='statistics',
            name='longEndCountTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='longEndCountTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longEndPnlTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='longEndPnlTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longEndWinsTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='longEndWinsTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longEndWrTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='longEndWrTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longEndsLostTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='longEndsLostTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longStartCountTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='longStartCountTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longStartLostCountTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='longStartLostCountTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longStartPnlTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='longStartPnlTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longStartWinsCountTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='longStartWinsCountTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longStartWrTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='longStartWrTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longToLongCountTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='longToLongCountTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longToLongLostCountTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='longToLongLostCountTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longToLongPnlTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='longToLongPnlTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longToLongWinCountTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='longToLongWinCountTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longToLongWrTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='longToLongWrTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longToShortCountTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='longToShortCountTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longToShortLostCountTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='longToShortLostCountTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longToShortPnlTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='longToShortPnlTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longToShortWinCountTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='longToShortWinCountTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longToShortWrTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='longToShortWrTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortEndCountTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='shortEndCountTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortEndLostCountTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='shortEndLostCountTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortEndPnlTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='shortEndPnlTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortEndWinsCountTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='shortEndWinsCountTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortEndWrTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='shortEndWrTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortStartCountTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='shortStartCountTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortStartLostCountTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='shortStartLostCountTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortStartPnlTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='shortStartPnlTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortStartWinsCountTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='shortStartWinsCountTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortStartWrTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='shortStartWrTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortToLongCountTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='shortToLongCountTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortToLongLostCountTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='shortToLongLostCountTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortToLongPnlTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='shortToLongPnlTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortToLongWinCountTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='shortToLongWinCountTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortToLongWrTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='shortToLongWrTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortToShortCountTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='shortToShortCountTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortToShortLostCountTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='shortToShortLostCountTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortToShortPnlTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='shortToShortPnlTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortToShortWinCountTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='shortToShortWinCountTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortToShortWrTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='shortToShortWrTotal'),
            preserve_default=False,
        ),
    ]
