# Generated by Django 4.0.2 on 2022-11-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total_statistics', '0035_statistics_longendcountactive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='shortEndWinsCountClosed',
            field=models.CharField(default=11, max_length=255, verbose_name='shortEndWinsCountClosed'),
            preserve_default=False,
        ),
    ]
