# Generated by Django 4.0.2 on 2022-11-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total_statistics', '0036_statistics_shortendwinscountclosed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='longEndsLostTotal',
        ),
        migrations.AddField(
            model_name='statistics',
            name='longEndLostTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='longEndLostTotal'),
            preserve_default=False,
        ),
    ]
