# Generated by Django 4.0.2 on 2022-11-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total_statistics', '0037_remove_statistics_longendslosttotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='longEndsLostActive',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='longEndsLostClosed',
        ),
        migrations.AddField(
            model_name='statistics',
            name='longEndLostActive',
            field=models.CharField(default=1, max_length=255, verbose_name='longEndLostActive'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longEndLostClosed',
            field=models.CharField(default=1, max_length=255, verbose_name='longEndLostClosed'),
            preserve_default=False,
        ),
    ]
