# Generated by Django 4.0.2 on 2022-11-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total_statistics', '0038_remove_statistics_longendslostactive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='longToShortWinCountActive',
            field=models.CharField(default=1, max_length=255, verbose_name='longToShortWinCountActive'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='longToShortWinCountClosed',
            field=models.CharField(default=1, max_length=255, verbose_name='longToShortWinCountClosed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='shortEndWinsCountActive',
            field=models.CharField(default=1, max_length=255, verbose_name='shortEndWinsCountActive'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statistics',
            name='longToShortWinCountTotal',
            field=models.CharField(max_length=255, verbose_name='longToShortWinCountTotal'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='shortEndWinsCountTotal',
            field=models.CharField(max_length=255, verbose_name='shortEndWinsCountTotal'),
        ),
    ]
