# Generated by Django 4.0.2 on 2022-11-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total_statistics', '0039_statistics_longtoshortwincountactive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='roiPctTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='roiPctTotal'),
            preserve_default=False,
        ),
    ]
