# Generated by Django 4.0.2 on 2022-11-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total_statistics', '0040_statistics_roipcttotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='roiPctHighTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='roiPctHighTotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='roiPctLowTotal',
            field=models.CharField(default=1, max_length=255, verbose_name='roiPctLowTotal'),
            preserve_default=False,
        ),
    ]
