# Generated by Django 4.0.2 on 2022-09-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeid', models.CharField(max_length=255, verbose_name='tradeid')),
                ('symbol', models.CharField(max_length=255, verbose_name='symbol')),
                ('status', models.CharField(max_length=255, verbose_name='status')),
                ('market', models.CharField(max_length=255, verbose_name='market')),
                ('pnl', models.CharField(max_length=255, verbose_name='pnl')),
                ('activePrice', models.CharField(max_length=255, verbose_name='activePrice')),
                ('rsi', models.CharField(max_length=255, verbose_name='rsi')),
                ('riskRewardRatio', models.CharField(max_length=255, verbose_name='riskRewardRatio')),
                ('risk', models.CharField(max_length=255, verbose_name='risk')),
                ('reward', models.CharField(max_length=255, verbose_name='reward')),
                ('date_of_pivot_A', models.CharField(max_length=255, verbose_name='date_of_pivot_A')),
                ('date_of_pivot_B', models.CharField(max_length=255, verbose_name='date_of_pivot_B')),
                ('price_of_pivot_A', models.CharField(max_length=255, verbose_name='price_of_pivot_A')),
                ('price_of_pivot_B', models.CharField(max_length=255, verbose_name='price_of_pivot_B')),
                ('date_supp_resistance_tested', models.CharField(max_length=255, verbose_name='date_pivot_A_snr_tested')),
                ('price_supp_resistance_tested', models.CharField(max_length=255, verbose_name='price_pivot_A_snr_tested')),
                ('date_entered_short', models.CharField(max_length=255, verbose_name='date_entered_short')),
                ('price_entered_short', models.CharField(max_length=255, verbose_name='price_entered_short')),
                ('a_close_mark', models.CharField(max_length=255, verbose_name='high_close_mark')),
                ('b_close_mark', models.CharField(max_length=255, verbose_name='low_close_mark')),
                ('durationOfTrade', models.CharField(max_length=255, verbose_name='tradeType')),
                ('ohlc', models.JSONField(null=True)),
            ],
        ),
    ]
