# Generated by Django 4.0.2 on 2022-10-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_remove_trade_dateclosedshort'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='length_AtoB',
            field=models.CharField(default=1, max_length=255, verbose_name='length_AtoB'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='length_AtoD',
            field=models.CharField(default=1, max_length=255, verbose_name='length_AtoD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='length_BtoC',
            field=models.CharField(default=1, max_length=255, verbose_name='length_BtoC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='length_CtoD',
            field=models.CharField(default=1, max_length=255, verbose_name='length_CtoD'),
            preserve_default=False,
        ),
    ]
