# Generated by Django 4.0.2 on 2022-10-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_trade_length_atob_trade_length_atod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='length_AtoB',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='length_AtoD',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='length_BtoC',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='length_CtoD',
        ),
    ]
