# Generated by Django 4.0.2 on 2022-10-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_trade_length_atob_trade_length_atod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='dateEnteredShort',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='dateofB',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='priceClosedShort',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='priceEnteredShort',
        ),
        migrations.AddField(
            model_name='trade',
            name='dateOfB',
            field=models.CharField(default=1, max_length=255, verbose_name='dateOfB'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='dateOfC',
            field=models.CharField(default=1, max_length=255, verbose_name='dateOfC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='priceOfC',
            field=models.CharField(default=1, max_length=255, verbose_name='priceOfC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='priceOfD',
            field=models.CharField(default=1, max_length=255, verbose_name='priceOfD'),
            preserve_default=False,
        ),
    ]
