# Generated by Django 4.0.2 on 2022-10-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_remove_trade_dateenteredshort_remove_trade_dateofb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='dateOfD',
            field=models.CharField(default=1, max_length=255, verbose_name='dateOfD'),
            preserve_default=False,
        ),
    ]
