# Generated by Django 4.0.2 on 2022-10-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0008_trade_dateofd'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='bcRetracement',
            field=models.CharField(default=1, max_length=255, verbose_name='bcRetracement'),
            preserve_default=False,
        ),
    ]
