# Generated by Django 4.0.2 on 2022-10-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0009_trade_bcretracement'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='initialTradeType',
            field=models.CharField(default=1, max_length=255, verbose_name='initialTradeType'),
            preserve_default=False,
        ),
    ]
