# Generated by Django 4.0.2 on 2022-10-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0010_trade_initialtradetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='type',
            field=models.CharField(default=1, max_length=255, verbose_name='tradeType'),
            preserve_default=False,
        ),
    ]
