# Generated by Django 4.0.2 on 2022-11-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0012_trade_returnpercentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='initialTradeType',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='tradeType',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='type',
        ),
        migrations.AddField(
            model_name='trade',
            name='closingTradeType',
            field=models.CharField(default=1, max_length=255, verbose_name='closingTradeType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='completeTradeType',
            field=models.CharField(default=1, max_length=255, verbose_name='completeTradeType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='openingTradeType',
            field=models.CharField(default=1, max_length=255, verbose_name='openingTradeType'),
            preserve_default=False,
        ),
    ]
