# Generated by Django 4.0.2 on 2022-11-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0014_trade_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='bcRetracement',
            field=models.CharField(max_length=25, verbose_name='bcRetracement'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='closingTradeType',
            field=models.CharField(max_length=25, verbose_name='closingTradeType'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='completeTradeType',
            field=models.CharField(max_length=25, verbose_name='completeTradeType'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='currentDate',
            field=models.CharField(max_length=25, verbose_name='currentDate'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='currentPrice',
            field=models.CharField(max_length=25, verbose_name='currentPrice'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='dateOfA',
            field=models.CharField(max_length=25, verbose_name='dateOfA'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='dateOfB',
            field=models.CharField(max_length=25, verbose_name='dateOfB'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='dateOfC',
            field=models.CharField(max_length=25, verbose_name='dateOfC'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='dateOfD',
            field=models.CharField(max_length=25, verbose_name='dateOfD'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='daysSinceStartDate',
            field=models.CharField(max_length=25, verbose_name='daysSinceStartDate'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='exchange',
            field=models.CharField(max_length=25, verbose_name='exchange'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='furthestOfA',
            field=models.CharField(max_length=25, verbose_name='furthestOfA'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='length_AtoB',
            field=models.CharField(max_length=25, verbose_name='length_AtoB'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='length_AtoD',
            field=models.CharField(max_length=25, verbose_name='length_AtoD'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='length_BtoC',
            field=models.CharField(max_length=25, verbose_name='length_BtoC'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='length_CtoD',
            field=models.CharField(max_length=25, verbose_name='length_CtoD'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='openingTradeType',
            field=models.CharField(max_length=25, verbose_name='openingTradeType'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='pivotPair',
            field=models.CharField(max_length=25, verbose_name='pivotPair'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='pnl',
            field=models.CharField(max_length=25, verbose_name='pnl'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='priceOfA',
            field=models.CharField(max_length=25, verbose_name='priceOfA'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='priceOfB',
            field=models.CharField(max_length=25, verbose_name='priceOfB'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='priceOfC',
            field=models.CharField(max_length=25, verbose_name='priceOfC'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='priceOfD',
            field=models.CharField(max_length=25, verbose_name='priceOfD'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='returnPercentage',
            field=models.CharField(max_length=25, verbose_name='returnPercentage'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='reward',
            field=models.CharField(max_length=25, verbose_name='reward'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='risk',
            field=models.CharField(max_length=25, verbose_name='risk'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='riskRewardRatio',
            field=models.CharField(max_length=25, verbose_name='riskRewardRatio'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='rsi',
            field=models.CharField(max_length=25, verbose_name='rsi'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='rsiOnEnter',
            field=models.CharField(max_length=25, verbose_name='rsiOnEnter'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='stockNameFull',
            field=models.CharField(max_length=25, verbose_name='stockNameFull'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='stockNameSymbol',
            field=models.CharField(max_length=25, verbose_name='stockNameSymbol'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='stopLoss',
            field=models.CharField(max_length=25, verbose_name='stopLoss'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='takeProfit',
            field=models.CharField(max_length=25, verbose_name='takeProfit'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='tradeCloseDate',
            field=models.CharField(max_length=25, verbose_name='tradeCloseDate'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='tradeClosed',
            field=models.CharField(max_length=25, verbose_name='tradeClosed'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='tradeDuration',
            field=models.CharField(max_length=25, verbose_name='tradeDuration'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='tradeID',
            field=models.CharField(max_length=25, verbose_name='tradeID'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='tradeOpen',
            field=models.CharField(max_length=25, verbose_name='tradeOpen'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='tradeResult',
            field=models.CharField(max_length=25, verbose_name='tradeResult'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='tradeStartDate',
            field=models.CharField(max_length=25, verbose_name='tradeStartDate'),
        ),
    ]
