# Generated by Django 4.0.2 on 2022-12-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0015_alter_trade_bcretracement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='settings',
            field=models.CharField(default=1, max_length=25, verbose_name='settings'),
            preserve_default=False,
        ),
    ]
