# Generated by Django 4.0.2 on 2022-12-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0016_trade_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='settings',
            field=models.CharField(max_length=500, verbose_name='settings'),
        ),
    ]
