# Generated by Django 4.0.2 on 2023-01-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0017_alter_trade_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='settingsName',
            field=models.CharField(default=1, max_length=25, verbose_name='settingsName'),
            preserve_default=False,
        ),
    ]
