# Generated by Django 4.0.2 on 2023-02-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0019_remove_trade_settings_trade_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='settings',
            field=models.JSONField(null=True),
        ),
    ]
