# Generated by Django 4.0.2 on 2023-02-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0021_trade_barlocations_trade_dates_trade_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='barLocations',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='price',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='status',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='type',
        ),
        migrations.AlterField(
            model_name='trade',
            name='pnl',
            field=models.CharField(default=1, max_length=25, verbose_name='pnl'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trade',
            name='rsi',
            field=models.CharField(default=1, max_length=25, verbose_name='rsi'),
            preserve_default=False,
        ),
    ]
