# Generated by Django 4.0.2 on 2023-02-08 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0022_remove_trade_barlocations_remove_trade_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='dates',
        ),
    ]
