# Generated by Django 4.0.2 on 2023-02-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0023_remove_trade_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='dates',
            field=models.JSONField(null=True),
        ),
    ]
