# Generated by Django 4.0.2 on 2023-02-08 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0024_trade_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='dates',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='settings',
        ),
    ]
