# Generated by Django 4.0.2 on 2023-02-08 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0025_remove_trade_dates_remove_trade_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='info',
        ),
    ]
