# Generated by Django 4.0.2 on 2023-02-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0026_remove_trade_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='barLocations',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='dates',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='duration',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='info',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='price',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='settings',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='status',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='type',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='pnl',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='rsi',
            field=models.JSONField(null=True),
        ),
    ]
