# Generated by Django 4.0.2 on 2023-02-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0027_trade_barlocations_trade_dates_trade_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='pivotA',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='pivotB',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='pivotC',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='pivotD',
            field=models.JSONField(null=True),
        ),
    ]
