# Generated by Django 4.0.2 on 2023-02-12 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0028_trade_pivota_trade_pivotb_trade_pivotc_trade_pivotd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='pivotD',
            new_name='pivotInfo',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='pivotA',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='pivotB',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='pivotC',
        ),
    ]
