# Generated by Django 4.0.2 on 2023-02-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0030_trade_cdretracement'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='enterExitInfo',
            field=models.JSONField(null=True),
        ),
    ]
