# Generated by Django 4.0.2 on 2023-02-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0031_trade_enterexitinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='movement',
            field=models.JSONField(null=True),
        ),
    ]
