# Generated by Django 4.0.2 on 2023-02-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0032_trade_movement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='info',
            new_name='tradeInfo',
        ),
        migrations.AddField(
            model_name='trade',
            name='retracement',
            field=models.JSONField(null=True),
        ),
    ]
