# Generated by Django 4.2.5 on 2024-01-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_patterns', '0002_pattern_abcd_current_date_selected_abcd_current_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern_abcd',
            name='d_dropped_below_d',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='selected_abcd',
            name='d_dropped_below_d',
            field=models.DateField(null=True),
        ),
    ]
