# Generated by Django 4.2.5 on 2024-01-19 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_patterns', '0003_pattern_abcd_d_dropped_below_d_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pattern_abcd',
            old_name='d_dropped_below_d',
            new_name='d_dropped_below_b',
        ),
        migrations.RenameField(
            model_name='selected_abcd',
            old_name='d_dropped_below_d',
            new_name='d_dropped_below_b',
        ),
    ]
