# Generated by Django 4.2.5 on 2024-01-24 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CandleData', '0001_initial'),
        ('all_patterns', '0004_rename_d_dropped_below_d_pattern_abcd_d_dropped_below_b_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatternAndCandles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CandleData.candle')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_patterns.pattern_abcd')),
            ],
        ),
    ]
