# Generated by Django 4.2.5 on 2024-01-24 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_patterns', '0005_patternandcandles'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern_abcd',
            name='candle_ids',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
