# Generated by Django 4.2.5 on 2024-01-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandleData', '0001_initial'),
        ('all_patterns', '0006_pattern_abcd_candle_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern_abcd',
            name='candles',
            field=models.ManyToManyField(to='CandleData.candle'),
        ),
    ]
