# Generated by Django 4.0.2 on 2022-09-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='strategySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ab=cd')),
                ('length', models.CharField(max_length=255, verbose_name='length')),
                ('aBelowb', models.CharField(max_length=255, verbose_name='list')),
                ('aToBLength', models.CharField(max_length=255, verbose_name='list')),
                ('bToShortLength', models.CharField(max_length=255, verbose_name='list')),
                ('marketType', models.CharField(max_length=255, verbose_name='list')),
                ('singlePivot', models.CharField(max_length=255, verbose_name='list')),
                ('isRsiActive', models.CharField(max_length=255, verbose_name='list')),
                ('rsi', models.CharField(max_length=255, verbose_name='list')),
                ('isPivotSteepnessActive', models.CharField(max_length=255, verbose_name='list')),
                ('isAbnormalPriceActive', models.CharField(max_length=255, verbose_name='list')),
            ],
        ),
    ]
