# Generated by Django 4.0.2 on 2023-05-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_settings', '0004_alter_strategysettings_settingsname'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategysettings',
            name='endDate',
            field=models.CharField(default=1, max_length=25, verbose_name='endDate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategysettings',
            name='startDate',
            field=models.CharField(default=1, max_length=25, verbose_name='startDate'),
            preserve_default=False,
        ),
    ]
