# Generated by Django 4.0.2 on 2023-05-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_settings', '0005_strategysettings_enddate_strategysettings_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategysettings',
            name='symbol',
            field=models.TextField(default=1, max_length=25, verbose_name='symbol'),
            preserve_default=False,
        ),
    ]
