# Generated by Django 4.2.5 on 2024-01-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('all_patterns', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Patterns_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100, null=True, unique=True)),
                ('total_abcds', models.IntegerField(null=True)),
                ('passed_abcds', models.IntegerField(null=True)),
                ('failed_abcds', models.IntegerField(null=True)),
                ('open_abcds', models.IntegerField(null=True)),
                ('passed_pct', models.FloatField(null=True)),
                ('abcd_length', models.IntegerField(null=True)),
                ('lowest_price_drop', models.FloatField(null=True)),
                ('average_lowest_price_drop', models.FloatField(null=True)),
                ('average_C_retracement', models.FloatField(null=True)),
                ('abcd_instances', models.ManyToManyField(blank=True, related_name='all_patterns_info', to='all_patterns.pattern_abcd')),
            ],
            options={
                'unique_together': {('symbol',)},
            },
        ),
    ]
