# Generated by Django 4.2.5 on 2024-01-11 15:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=500, null=True)),
                ('name', models.CharField(max_length=500, null=True)),
                ('exchange', models.CharField(max_length=500, null=True)),
                ('assetType', models.CharField(max_length=500, null=True)),
                ('ipoDate', models.CharField(max_length=500, null=True)),
                ('delistingDate', models.CharField(max_length=500, null=True)),
                ('status', models.CharField(max_length=500, null=True)),
            ],
            options={
                'unique_together': {('symbol', 'name', 'exchange', 'assetType', 'ipoDate', 'delistingDate')},
            },
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candle_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('symbol', models.CharField(max_length=100)),
                ('candle_date', models.DateField()),
                ('candle_open', models.FloatField()),
                ('candle_high', models.FloatField()),
                ('candle_low', models.FloatField()),
                ('candle_close', models.FloatField()),
                ('candle_volume', models.FloatField()),
            ],
            options={
                'unique_together': {('symbol', 'candle_date')},
            },
        ),
    ]
