# Generated by Django 4.2.5 on 2024-01-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandleData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedCandles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('candle_date', models.DateField()),
                ('candle_open', models.FloatField()),
                ('candle_high', models.FloatField()),
                ('candle_low', models.FloatField()),
                ('candle_close', models.FloatField()),
                ('candle_volume', models.FloatField()),
            ],
        ),
    ]
