# Generated by Django 4.2.5 on 2024-01-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandleData', '0002_selectedcandles'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedcandles',
            name='trade_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
